export type GameExperience = {
  id: string
  title: string
  world: string
  subject: string
  levels: string
  skill: string
  mission: string
  accessibility: string[]
  status: 'playable' | 'development'
  route?: string
}

export const gameExperiences: GameExperience[] = [
  {
    id: 'bosque-inferencias',
    title: 'Bosque de las inferencias',
    world: 'Bosque nativo 3D',
    subject: 'Lenguaje',
    levels: '3°–5° básico',
    skill: 'Inferir y justificar con evidencia',
    mission: 'Explorar pistas del entorno, relacionarlas y defender una inferencia antes de avanzar.',
    accessibility: ['audio opcional','movimiento reducido','alto contraste','teclado'],
    status: 'playable',
    route: '#bosque-inferencias',
  },
  {
    id: 'feria-matematica',
    title: 'Feria matemática',
    world: 'Feria escolar 3D',
    subject: 'Matemática',
    levels: '3°–6° básico',
    skill: 'Resolver problemas con dinero y operaciones',
    mission: 'Comprar, combinar precios, calcular vuelto y planificar un presupuesto para completar encargos.',
    accessibility: ['dinero visual','teclado','alto contraste','movimiento reducido','apoyo paso a paso'],
    status: 'playable',
    route: '#feria-matematica',
  },
  {
    id: 'mision-agua',
    title: 'Misión agua',
    world: 'Ciudad sostenible 3D',
    subject: 'Ciencias',
    levels: '5°–7° básico',
    skill: 'Aplicar ciclo del agua y consumo responsable',
    mission: 'Recuperar el suministro de una comunidad resolviendo desafíos científicos y de decisión.',
    accessibility: ['pistas graduadas','roles colaborativos','alternativa textual'],
    status: 'development',
  },
  {
    id: 'laboratorio-ecosistemas',
    title: 'Laboratorio de ecosistemas',
    world: 'Laboratorio + hábitats 3D',
    subject: 'Ciencias',
    levels: '4°–6° básico',
    skill: 'Relacionar componentes bióticos y abióticos',
    mission: 'Reconstruir ecosistemas equilibrados y explicar qué ocurre al modificar una variable.',
    accessibility: ['modo observación','etiquetas visuales','respuesta oral'],
    status: 'development',
  },
  {
    id: 'ruta-chile',
    title: 'Ruta por Chile',
    world: 'Mapa inmersivo de Chile',
    subject: 'Historia y Geografía',
    levels: '2°–6° básico',
    skill: 'Ubicar, comparar y relacionar territorio y cultura',
    mission: 'Viajar por macrozonas, resolver encargos locales y construir un pasaporte geográfico.',
    accessibility: ['mapa simplificado','audio descriptivo','íconos de apoyo'],
    status: 'development',
  },
  {
    id: 'museo-historias',
    title: 'Museo de las historias',
    world: 'Museo interactivo 3D',
    subject: 'Lenguaje',
    levels: '5° básico–2° medio',
    skill: 'Analizar narrador, conflicto, personajes y símbolos',
    mission: 'Investigar salas narrativas, descubrir relaciones entre objetos y construir una interpretación.',
    accessibility: ['lectura graduada','glosario','respuesta multimodal'],
    status: 'development',
  },
  {
    id: 'ciudad-fracciones',
    title: 'Ciudad de las fracciones',
    world: 'Ciudad modular 3D',
    subject: 'Matemática',
    levels: '4°–7° básico',
    skill: 'Representar, comparar y operar fracciones',
    mission: 'Completar construcciones usando partes equivalentes y justificar cada decisión matemática.',
    accessibility: ['modelos concretos','representación múltiple','andamiaje'],
    status: 'development',
  },
  {
    id: 'cuerpo-humano',
    title: 'Expedición cuerpo humano',
    world: 'Exploración anatómica 3D',
    subject: 'Ciencias',
    levels: '5°–8° básico',
    skill: 'Relacionar estructuras y funciones',
    mission: 'Recorrer sistemas del cuerpo, resolver incidentes y explicar cómo cooperan sus órganos.',
    accessibility: ['capas visuales','narración','modo sin tiempo'],
    status: 'development',
  },
  {
    id: 'espacio-proporciones',
    title: 'Base espacial',
    world: 'Estación orbital 3D',
    subject: 'Matemática',
    levels: '6° básico–1° medio',
    skill: 'Razón, proporción y resolución de problemas',
    mission: 'Administrar oxígeno, energía y suministros usando proporciones para mantener operativa la base.',
    accessibility: ['tablas visuales','calculadora opcional','pistas graduadas'],
    status: 'development',
  },
  {
    id: 'granja-palabras',
    title: 'Granja de palabras',
    world: 'Granja animada 3D',
    subject: 'Lenguaje',
    levels: 'Kínder–2° básico',
    skill: 'Conciencia fonológica y vocabulario',
    mission: 'Clasificar sonidos, reunir sílabas y ayudar a los personajes a completar palabras significativas.',
    accessibility: ['audio lento','pictogramas','interacción simple'],
    status: 'development',
  },
  {
    id: 'trazos-magicos',
    title: 'Senderos de trazos',
    world: 'Jardín fantástico 3D',
    subject: 'Grafomotricidad',
    levels: 'Prekínder–1° básico',
    skill: 'Direccionalidad y control grafomotor',
    mission: 'Recorrer senderos verticales, horizontales, inclinados, curvos, espirales, ondas, zigzag, bucles y arcos.',
    accessibility: ['trazo grueso','mano izquierda','sin límite de tiempo'],
    status: 'development',
  },
  {
    id: 'mercado-lectura',
    title: 'Mercado de pistas',
    world: 'Mercado barrial 3D',
    subject: 'Lenguaje',
    levels: '2°–5° básico',
    skill: 'Comprensión literal e inferencial',
    mission: 'Leer carteles, diálogos y encargos para deducir qué necesita cada personaje y por qué.',
    accessibility: ['lectura en voz alta','texto ampliado','apoyo visual'],
    status: 'development',
  },
]
