export type GameExperience = {
  id: string
  title: string
  world: string
  subject: string
  levels: string
  skill: string
  mission: string
  accessibility: string[]
  status: 'playable' | 'development'
  route?: string
}

export const gameExperiences: GameExperience[] = [
  {
    id: 'bosque-inferencias',
    title: 'Bosque de las inferencias',
    world: 'Bosque nativo 3D',
    subject: 'Lenguaje',
    levels: '3°–5° básico',
    skill: 'Inferir y justificar con evidencia',
    mission: 'Explorar pistas del entorno, relacionarlas y defender una inferencia antes de avanzar.',
    accessibility: ['audio opcional','movimiento reducido','alto contraste','teclado'],
    status: 'playable',
    route: '#bosque-inferencias',
  },
  {
    id: 'feria-matematica',
    title: 'Feria matemática',
    world: 'Feria escolar 3D',
    subject: 'Matemática',
    levels: '3°–6° básico',
    skill: 'Resolver problemas con dinero y operaciones',
    mission: 'Comprar, combinar precios, calcular vuelto y planificar un presupuesto para completar encargos.',
    accessibility: ['dinero visual','teclado','alto contraste','movimiento reducido','apoyo paso a paso'],
    status: 'playable',
    route: '#feria-matematica',
  },
  {
    id: 'mision-agua',
    title: 'Misión agua',
    world: 'Ciudad sostenible 3D',
    subject: 'Ciencias',
    levels: '5°–7° básico',
    skill: 'Aplicar ciclo del agua, consumo responsable y relaciones causa-efecto',
    mission: 'Recuperar el suministro de una comunidad equilibrando ahorro, tratamiento, protección de fuentes e impacto ambiental.',
    accessibility: ['alternativa textual','alto contraste','movimiento reducido','sin límite de tiempo','feedback causal'],
    status: 'playable',
    route: '#mision-agua',
  },
  {
    id: 'laboratorio-ecosistemas',
    title: 'Laboratorio de ecosistemas',
    world: 'Laboratorio + hábitats 3D',
    subject: 'Ciencias',
    levels: '4°–6° básico',
    skill: 'Relacionar componentes bióticos, abióticos y presiones ambientales',
    mission: 'Modificar agua, luz, biodiversidad y contaminación, ejecutar simulaciones y explicar cómo cada variable afecta el equilibrio del sistema.',
    accessibility: ['alternativa textual','alto contraste','movimiento reducido','sin límite de tiempo','bitácora de observación'],
    status: 'playable',
    route: '/juegos/laboratorio-ecosistemas',
  },
  {
    id: 'ruta-chile',
    title: 'Ruta por Chile',
    world: 'Mapa inmersivo de Chile',
    subject: 'Historia y Geografía',
    levels: '2°–6° básico',
    skill: 'Ubicar y relacionar macrozonas, clima, relieve y paisaje',
    mission: 'Viajar por cuatro macrozonas, interpretar pistas territoriales, decidir destinos y completar un pasaporte geográfico.',
    accessibility: ['mapa 3D + texto','audio opcional','alto contraste','movimiento reducido','sin límite de tiempo','nombres de macrozonas siempre visibles'],
    status: 'playable',
    route: '/juegos/ruta-chile',
  },
  {
    id: 'museo-historias',
    title: 'Museo de las historias',
    world: 'Museo interactivo 3D',
    subject: 'Lenguaje',
    levels: '5° básico–2° medio',
    skill: 'Analizar narrador, conflicto, personajes y símbolos',
    mission: 'Investigar salas narrativas, descubrir relaciones entre objetos y construir una interpretación.',
    accessibility: ['lectura graduada','glosario','respuesta multimodal'],
    status: 'development',
  },
  {
    id: 'ciudad-fracciones',
    title: 'Ciudad de las fracciones',
    world: 'Ciudad modular 3D',
    subject: 'Matemática',
    levels: '4°–7° básico',
    skill: 'Representar, comparar y construir fracciones',
    mission: 'Resolver tres distritos con equivalencias, comparación y construcción modular de fracciones, justificando cada decisión con una representación visual.',
    accessibility: ['modelo 3D + texto','lectura en voz alta opcional','alto contraste','movimiento reducido','sin límite de tiempo','retroalimentación inmediata'],
    status: 'playable',
    route: '/juegos/ciudad-fracciones',
  },
  {
    id: 'cuerpo-humano',
    title: 'Expedición cuerpo humano',
    world: 'Exploración anatómica 3D',
    subject: 'Ciencias',
    levels: '5°–8° básico',
    skill: 'Relacionar estructuras y funciones',
    mission: 'Recorrer sistemas del cuerpo, resolver incidentes y explicar cómo cooperan sus órganos.',
    accessibility: ['capas visuales','narración','modo sin tiempo'],
    status: 'development',
  },
  {
    id: 'espacio-proporciones',
    title: 'Base espacial',
    world: 'Estación orbital 3D',
    subject: 'Matemática',
    levels: '6° básico–1° medio',
    skill: 'Razón, proporción y resolución de problemas',
    mission: 'Administrar oxígeno, energía y suministros usando proporciones para mantener operativa la base.',
    accessibility: ['tablas visuales','calculadora opcional','pistas graduadas'],
    status: 'development',
  },
  {
    id: 'granja-palabras',
    title: 'Granja de palabras',
    world: 'Granja animada 3D',
    subject: 'Lenguaje',
    levels: 'Kínder–2° básico',
    skill: 'Conciencia fonológica, sonido inicial y construcción silábica',
    mission: 'Escuchar un fonema, encontrar la palabra que comienza con ese sonido y construirla ordenando sílabas.',
    accessibility: ['audio opcional','palabra escrita','alternativa textual','alto contraste','movimiento reducido','sin límite de tiempo'],
    status: 'playable',
    route: '/juegos/granja-palabras',
  },
  {
    id: 'trazos-magicos',
    title: 'Senderos de trazos',
    world: 'Jardín fantástico 3D',
    subject: 'Grafomotricidad',
    levels: 'Prekínder–1° básico',
    skill: 'Direccionalidad y control grafomotor',
    mission: 'Recorrer senderos verticales, horizontales, inclinados, curvos, espirales, ondas, zigzag, bucles y arcos.',
    accessibility: ['trazo grueso','mano izquierda','sin límite de tiempo'],
    status: 'development',
  },
  {
    id: 'mercado-lectura',
    title: 'Mercado de pistas',
    world: 'Mercado barrial 3D',
    subject: 'Lenguaje',
    levels: '2°–5° básico',
    skill: 'Comprensión literal e inferencial',
    mission: 'Leer carteles, diálogos y encargos para deducir qué necesita cada personaje y por qué.',
    accessibility: ['lectura en voz alta','texto ampliado','apoyo visual'],
    status: 'development',
  },
]
