import type { Metadata } from 'next'
import Link from 'next/link'
import {
  Activity,
  ArrowRight,
  BarChart3,
  BellRing,
  BookOpen,
  Bot,
  BrainCircuit,
  CalendarDays,
  CheckCircle2,
  ChevronRight,
  ClipboardCheck,
  FileText,
  Gamepad2,
  GraduationCap,
  HeartHandshake,
  Layers3,
  Library,
  LineChart,
  LockKeyhole,
  MessagesSquare,
  Network,
  School,
  ShieldCheck,
  Sparkles,
  Target,
  Users