import type { PremiumActivity } from './premiumActivities'

export const additionalActivities: PremiumActivity[] = [
  {
    slug: 'secuencia-cuento-visual', title: 'Ordenamos el cuento paso a paso', subject: 'Lenguaje', level: '2.º–3.º básico', oa: 'OA 3', format: 'Secuencia visual', duration: '25 min', illustration: 'reading',
    summary: 'Actividad para ordenar acciones, reconocer inicio, desarrollo y final, y relatar una historia breve.',
    goal: 'Ordenar acontecimientos y reconstruir una narración con coherencia.',
    steps: ['Observar cuatro escenas.', 'Leer las acciones.', 'Ordenar del 1 al 4.', 'Relatar oralmente.', 'Escribir una oración final.'],
    supports: ['Imágenes grandes', 'Lectura mediada', 'Respuesta oral', 'Frases incompletas', 'Menos distractores'],
    success: ['Ordena al menos tres escenas.', 'Usa conectores temporales.', 'Reconoce el desenlace.'],
    content: { type: 'sequence', title: 'La semilla de Ana', body: 'Ana plantó una semilla y la cuidó durante varios días.', items: ['Ana prepara la tierra.', 'Coloca la semilla.', 'Riega la maceta.', 'Aparece una planta.'] },
  },
  {
    slug: 'vocabulario-contexto', title: 'Palabras detectives', subject: 'Lenguaje', level: '3.º–4.º básico', oa: 'OA 10', format: 'Juego de vocabulario', duration: '30 min', illustration: 'forest',
    summary: 'Descubrimiento del significado de palabras usando pistas de la oración y del párrafo.',
    goal: 'Inferir el significado de palabras desconocidas a partir del contexto.',
    steps: ['Leer la oración.', 'Subrayar pistas.', 'Elegir un significado.', 'Comprobar reemplazando la palabra.', 'Crear una nueva oración.'],
    supports: ['Glosario visual', 'Audio', 'Opciones reducidas', 'Colores por pista', 'Respuesta oral'],
    success: ['Identifica pistas contextuales.', 'Selecciona un significado coherente.', 'Usa la palabra en una oración.'],
    content: { type: 'text', title: 'La palabra misteriosa', body: 'El perro quedó exhausto después de correr durante toda la tarde. Se acostó y no quiso moverse.', items: ['¿Qué significa exhausto?', '¿Qué pista ayuda?', 'Escribe un sinónimo.'] },
  },
  {
    slug: 'comprension-noticia', title: 'Leemos una noticia escolar', subject: 'Lenguaje', level: '4.º–5.º básico', oa: 'OA 6', format: 'Noticia + guía', duration: '35 min', illustration: 'reading',
    summary: 'Lectura de una noticia breve para identificar titular, hechos, lugar, fecha y propósito.',
    goal: 'Comprender información explícita y estructura de una noticia.',
    steps: ['Observar el titular.', 'Leer la noticia.', 'Responder qué, quién, cuándo y dónde.', 'Distinguir hecho de opinión.', 'Crear un nuevo titular.'],
    supports: ['Texto segmentado', 'Palabras clave', 'Audio', 'Preguntas graduadas', 'Versión ampliada'],
    success: ['Localiza información explícita.', 'Reconoce el propósito.', 'Distingue hecho y opinión.'],
    content: { type: 'text', title: 'Nueva huerta en la escuela', body: 'El viernes 24 de julio, estudiantes de quinto básico inauguraron una huerta escolar en el patio central. La actividad contó con apoyo de las familias y docentes.', items: ['¿Qué ocurrió?', '¿Cuándo?', '¿Quiénes participaron?', 'Escribe un titular alternativo.'] },
  },
  {
    slug: 'sumas-reserva', title: 'Taller de sumas con reserva', subject: 'Matemática', level: '2.º–3.º básico', oa: 'OA 6', format: 'Tutor paso a paso', duration: '30 min', illustration: 'placevalue',
    summary: 'Práctica guiada de adiciones con reagrupación usando bloques y algoritmo vertical.',
    goal: 'Resolver adiciones con reserva comprendiendo el reagrupamiento.',
    steps: ['Representar unidades y decenas.', 'Sumar unidades.', 'Cambiar 10 unidades por una decena.', 'Sumar decenas.', 'Comprobar.'],
    supports: ['Bloques base diez', 'Cuadrícula', 'Colores posicionales', 'Ejemplo resuelto', 'Audio de pasos'],
    success: ['Alinea cifras.', 'Realiza la reserva correctamente.', 'Comprueba el resultado.'],
    content: { type: 'math', title: 'Resuelve 278 + 146', body: 'Usa unidades, decenas y centenas para explicar cada paso.', items: ['8 + 6 = 14', 'Escribe 4 y reserva 1 decena', '7 + 4 + 1 = 12', 'Resultado: 424'] },
  },
  {
    slug: 'restas-canjes', title: 'Resta con canje visual', subject: 'Matemática', level: '2.º–3.º básico', oa: 'OA 6', format: 'Manipulativo', duration: '30 min', illustration: 'placevalue',
    summary: 'Restas con descomposición y canje usando material base diez y registro vertical.',
    goal: 'Comprender el canje en sustracciones con reserva.',
    steps: ['Representar el minuendo.', 'Revisar si alcanzan las unidades.', 'Canjear una decena.', 'Restar por posición.', 'Verificar sumando.'],
    supports: ['Material concreto', 'Paso único por pantalla', 'Cuadrícula', 'Narración', 'Modo sin tiempo'],
    success: ['Realiza el canje.', 'Mantiene orden posicional.', 'Verifica con una suma.'],
    content: { type: 'math', title: 'Resuelve 403 − 178', body: 'Descompón una centena cuando sea necesario.', items: ['Canjea 1 centena por 10 decenas', 'Canjea 1 decena por 10 unidades', 'Resultado: 225'] },
  },
  {
    slug: 'fracciones-cocina', title: 'Cocina de fracciones', subject: 'Matemática', level: '4.º–5.º básico', oa: 'OA 8', format: 'Simulación', duration: '35 min', illustration: 'market',
    summary: 'Representación y comparación de fracciones mediante recetas, porciones y equivalencias.',
    goal: 'Representar fracciones y reconocer equivalencias sencillas.',
    steps: ['Dividir una receta en partes.', 'Representar la fracción.', 'Comparar porciones.', 'Buscar una equivalencia.', 'Resolver un desafío.'],
    supports: ['Modelos circulares', 'Colores', 'Lectura de fracciones', 'Pistas', 'Respuesta manipulativa'],
    success: ['Identifica numerador y denominador.', 'Representa una fracción.', 'Reconoce una equivalencia.'],
    content: { type: 'math', title: 'Preparamos una pizza', body: 'La pizza se divide en 8 partes iguales y se comen 4.', items: ['Fracción comida: 4/8', 'Fracción equivalente: 1/2', 'Fracción restante: 4/8'] },
  },
  {
    slug: 'perimetro-patio', title: 'Diseña el patio escolar', subject: 'Matemática', level: '4.º–5.º básico', oa: 'OA 21', format: 'Proyecto breve', duration: '40 min', illustration: 'placevalue',
    summary: 'Cálculo de perímetro y área en planos sencillos del entorno escolar.',
    goal: 'Calcular perímetro y área de rectángulos en situaciones concretas.',
    steps: ['Leer las medidas.', 'Dibujar el plano.', 'Calcular perímetro.', 'Calcular área.', 'Comparar diseños.'],
    supports: ['Cuadrícula', 'Fórmulas visibles', 'Modelo resuelto', 'Calculadora opcional', 'Trabajo en pareja'],
    success: ['Distingue perímetro y área.', 'Usa unidades correctas.', 'Explica el procedimiento.'],
    content: { type: 'math', title: 'Patio rectangular', body: 'El patio mide 12 m de largo y 8 m de ancho.', items: ['Perímetro = 40 m', 'Área = 96 m²', 'Dibuja otra forma con igual perímetro.'] },
  },
  {
    slug: 'angulos-entorno', title: 'Cazadores de ángulos', subject: 'Matemática', level: '5.º básico', oa: 'OA 18', format: 'Exploración + PAES', duration: '40 min', illustration: 'placevalue',
    summary: 'Identificación, estimación y clasificación de ángulos en objetos cotidianos.',
    goal: 'Reconocer ángulos agudos, rectos, obtusos y extendidos.',
    steps: ['Observar objetos.', 'Estimar el tipo de ángulo.', 'Medir con transportador.', 'Clasificar.', 'Resolver preguntas tipo PAES.'],
    supports: ['Transportador virtual', 'Ejemplos visuales', 'Alto contraste', 'Pistas graduadas', 'Respuesta por selección'],
    success: ['Clasifica correctamente.', 'Usa el transportador.', 'Justifica comparando con 90°.'],
    content: { type: 'math', title: 'Ángulos del colegio', body: 'Observa una puerta abierta, una esquina de cuaderno y una escalera.', items: ['Puerta a 45°: agudo', 'Esquina: recto', 'Escalera abierta: obtuso'] },
  },
  {
    slug: 'ciclo-agua', title: 'El viaje de una gota', subject: 'Ciencias', level: '3.º–4.º básico', oa: 'OA 11', format: 'Animación + secuencia', duration: '35 min', illustration: 'ecosystem',
    summary: 'Comprensión del ciclo del agua mediante secuencia, experimento y explicación visual.',
    goal: 'Explicar evaporación, condensación y precipitación.',
    steps: ['Observar la animación.', 'Ordenar etapas.', 'Realizar un experimento simple.', 'Registrar cambios.', 'Explicar el ciclo.'],
    supports: ['Animación lenta', 'Pictogramas', 'Glosario', 'Respuesta oral', 'Texto simple'],
    success: ['Ordena las etapas.', 'Relaciona calor y evaporación.', 'Explica el retorno del agua.'],
    content: { type: 'science', title: 'De la nube al río', body: 'El agua cambia de estado y circula continuamente en la naturaleza.', items: ['Evaporación', 'Condensación', 'Precipitación', 'Acumulación'] },
  },
  {
    slug: 'sistema-solar', title: 'Misión sistema solar', subject: 'Ciencias', level: '3.º–4.º básico', oa: 'OA 12', format: 'Simulación', duration: '40 min', illustration: 'ecosystem',
    summary: 'Exploración del sistema solar, movimientos de la Tierra y características básicas de los planetas.',
    goal: 'Reconocer componentes del sistema solar y movimientos de la Tierra.',
    steps: ['Explorar el modelo.', 'Ordenar planetas.', 'Comparar tamaños.', 'Simular rotación y traslación.', 'Responder un desafío.'],
    supports: ['Narración', 'Zoom', 'Etiquetas', 'Modo alto contraste', 'Glosario'],
    success: ['Ubica la Tierra.', 'Distingue rotación y traslación.', 'Reconoce al Sol como estrella.'],
    content: { type: 'science', title: 'La Tierra en movimiento', body: 'La Tierra gira sobre sí misma y también alrededor del Sol.', items: ['Rotación: día y noche', 'Traslación: año', 'El Sol es una estrella'] },
  },
  {
    slug: 'cuerpo-humano-salud', title: 'Guardianes del cuerpo', subject: 'Ciencias', level: '5.º básico', oa: 'OA 6', format: 'Caso interactivo', duration: '35 min', illustration: 'circuit',
    summary: 'Relación entre hábitos saludables y funcionamiento de sistemas del cuerpo humano.',
    goal: 'Explicar cómo alimentación, descanso y ejercicio favorecen la salud.',
    steps: ['Leer un caso.', 'Identificar hábitos.', 'Relacionar con sistemas.', 'Proponer mejoras.', 'Crear un plan saludable.'],
    supports: ['Infografías', 'Audio', 'Organizador gráfico', 'Respuesta oral', 'Vocabulario simple'],
    success: ['Reconoce hábitos protectores.', 'Relaciona hábito y efecto.', 'Propone una acción concreta.'],
    content: { type: 'science', title: 'El día de Tomás', body: 'Tomás duerme poco, no desayuna y pasa varias horas sentado.', items: ['Identifica dos riesgos.', 'Propón tres cambios.', 'Explica un beneficio.'] },
  },
  {
    slug: 'romanos-legado', title: 'Viaje al legado romano', subject: 'Historia', level: '5.º básico', oa: 'OA 3', format: 'Tarjetas de estudio', duration: '35 min', illustration: 'market',
    summary: 'Cinco estaciones sobre Coliseo, Panteón, caminos, leyes y lengua latina.',
    goal: 'Reconocer monumentos y aportes del mundo romano.',
    steps: ['Explorar tarjetas.', 'Ubicar Roma.', 'Comparar monumentos.', 'Relacionar legados actuales.', 'Preparar una exposición breve.'],
    supports: ['Textos breves', 'Imágenes', 'Palabras clave', 'Audio', 'Guion de exposición'],
    success: ['Describe dos monumentos.', 'Nombra tres legados.', 'Expone con apoyo visual.'],
    content: { type: 'text', title: 'Roma sigue presente', body: 'Los romanos construyeron caminos, edificios y leyes que influyen hasta hoy.', items: ['Coliseo', 'Panteón', 'Derecho romano', 'Latín', 'Caminos'] },
  },
  {
    slug: 'conquista-america', title: 'Ruta de la conquista de América', subject: 'Historia', level: '5.º básico', oa: 'OA 2', format: 'Línea de tiempo', duration: '40 min', illustration: 'market',
    summary: 'Proceso de exploración, conquista y consecuencias mediante mapa y secuencia cronológica.',
    goal: 'Comprender causas, etapas y consecuencias de la conquista.',
    steps: ['Analizar motivaciones.', 'Seguir rutas.', 'Ordenar acontecimientos.', 'Comparar perspectivas.', 'Registrar consecuencias.'],
    supports: ['Mapa visual', 'Lectura simple', 'Línea de tiempo', 'Glosario', 'Respuesta guiada'],
    success: ['Ordena hechos principales.', 'Reconoce motivaciones.', 'Explica dos consecuencias.'],
    content: { type: 'sequence', title: 'Del viaje al encuentro', body: 'Los viajes europeos iniciaron un proceso de profundas transformaciones.', items: ['Financiamiento del viaje', 'Llegada a América', 'Conquista de imperios', 'Llegada a Chile', 'Consecuencias culturales y sanitarias'] },
  },
  {
    slug: 'flora-nativa', title: 'Herbario de flora centro-sur', subject: 'Ciencias', level: '3.º–5.º básico', oa: 'OA 2', format: 'Herbario digital', duration: '45 min', illustration: 'forest',
    summary: 'Fichas de especies nativas con características, hábitat y acciones de cuidado.',
    goal: 'Reconocer flora nativa de la zona centro-sur de Chile.',
    steps: ['Observar la especie.', 'Leer su característica.', 'Ubicar hábitat.', 'Comparar hojas y flores.', 'Crear una ficha.'],
    supports: ['Fotografías', 'Texto breve', 'Audio', 'Zoom', 'Plantilla editable'],
    success: ['Identifica especies.', 'Describe una característica.', 'Propone una acción de cuidado.'],
    content: { type: 'science', title: 'Plantas de nuestro entorno', body: 'La flora nativa está adaptada al clima y sostiene numerosos ecosistemas.', items: ['Copihue', 'Boldo', 'Peumo', 'Quillay', 'Araucaria'] },
  },
  {
    slug: 'convivencia-emociones', title: 'Semáforo de emociones', subject: 'Orientación', level: '1.º–5.º básico', oa: 'Convivencia', format: 'Tablero interactivo', duration: '15 min', illustration: 'routine',
    summary: 'Identificación emocional, estrategias de regulación y solicitud adecuada de apoyo.',
    goal: 'Reconocer el estado emocional y elegir una estrategia de regulación.',
    steps: ['Identificar emoción.', 'Elegir color del semáforo.', 'Nombrar una causa.', 'Seleccionar estrategia.', 'Revisar cómo se siente.'],
    supports: ['Pictogramas', 'Escala visual', 'Audio', 'Tiempo afuera', 'Respuesta no verbal'],
    success: ['Reconoce su emoción.', 'Elige una estrategia.', 'Solicita ayuda respetuosamente.'],
    content: { type: 'sequence', title: 'Paro, pienso y actúo', body: 'El semáforo ayuda a detenerse y elegir una respuesta segura.', items: ['Rojo: me detengo', 'Amarillo: respiro y pienso', 'Verde: elijo una acción'] },
  },
  {
    slug: 'atencion-instrucciones', title: 'Misión: sigue la instrucción', subject: 'PIE / DUA', level: '1.º–4.º básico', oa: 'Acceso', format: 'Entrenamiento ejecutivo', duration: '20 min', illustration: 'routine',
    summary: 'Práctica progresiva de instrucciones de uno, dos y tres pasos con apoyos visuales.',
    goal: 'Mejorar comprensión, memoria de trabajo y seguimiento de instrucciones.',
    steps: ['Escuchar.', 'Repetir la instrucción.', 'Observar pictogramas.', 'Realizar los pasos.', 'Autoevaluar.'],
    supports: ['Una instrucción por vez', 'Pictogramas', 'Repetición', 'Temporizador', 'Refuerzo positivo'],
    success: ['Inicia sin demora.', 'Completa pasos en orden.', 'Pide repetición cuando la necesita.'],
    content: { type: 'sequence', title: 'Tres pasos para comenzar', body: 'Escucha y realiza cada acción en orden.', items: ['Saca el cuaderno.', 'Escribe la fecha.', 'Subraya el título.'] },
  },
  {
    slug: 'discapacidad-visual-acceso', title: 'Lectura de alto contraste', subject: 'PIE / DUA', level: 'Multinivel', oa: 'Acceso', format: 'Material accesible', duration: '20 min', illustration: 'reading',
    summary: 'Texto ampliado con contraste, espaciado y alternativas de acceso para estudiantes con baja visión.',
    goal: 'Acceder a un texto informativo mediante adecuaciones visuales.',
    steps: ['Seleccionar contraste.', 'Ajustar tamaño.', 'Leer por fragmentos.', 'Responder oral o escrito.', 'Registrar preferencia visual.'],
    supports: ['Arial ampliada', 'Negro sobre amarillo', 'Interlineado 1,5', 'Lectura mediada', 'Atril sugerido'],
    success: ['Mantiene postura adecuada.', 'Localiza información.', 'Expresa la modalidad que facilita su acceso.'],
    content: { type: 'text', title: 'El pudú', body: 'El pudú es uno de los ciervos más pequeños del mundo. Vive en bosques del sur de Chile y se alimenta de hojas y frutos.', items: ['¿Dónde vive?', '¿De qué se alimenta?', 'Nombra una característica.'] },
  },
  {
    slug: 'ticket-salida', title: 'Ticket de salida inteligente', subject: 'Evaluación', level: 'Multinivel', oa: 'Formativa', format: 'Evaluación rápida', duration: '8 min', illustration: 'assessment',
    summary: 'Cierre de clase adaptable con tres preguntas y autoevaluación visual.',
    goal: 'Recoger evidencia inmediata del aprendizaje y nivel de seguridad.',
    steps: ['Responder qué aprendí.', 'Resolver un ejemplo.', 'Marcar nivel de seguridad.', 'Indicar apoyo necesario.', 'Enviar evidencia.'],
    supports: ['Respuesta oral', 'Escala visual', 'Texto simple', 'Pictogramas', 'Una pregunta por pantalla'],
    success: ['Expresa un aprendizaje.', 'Aplica la habilidad.', 'Identifica si necesita apoyo.'],
    content: { type: 'text', title: 'Antes de salir', body: 'Piensa en el objetivo de la clase y responde con tus propias palabras.', items: ['Hoy aprendí...', 'Un ejemplo es...', 'Necesito practicar...'] },
  },
]
