import type { PremiumActivity } from './premiumActivities'

type Seed = Omit<PremiumActivity, 'steps' | 'supports' | 'success'> & {
  steps?: string[]
  supports?: string[]
  success?: string[]
}

const commonSteps = ['Activar conocimientos previos.','Modelar un ejemplo.','Realizar práctica guiada.','Resolver el desafío principal.','Cerrar con autoevaluación.']
const commonSupports = ['Instrucciones breves','Apoyo visual','Respuesta oral o escrita','Tiempo adicional','Modelado paso a paso']
const commonSuccess = ['Comprende la instrucción.','Aplica la estrategia trabajada.','Explica o demuestra su respuesta.']

const activity = (seed: Seed): PremiumActivity => ({
  ...seed,
  steps: seed.steps ?? commonSteps,
  supports: seed.supports ?? commonSupports,
  success: seed.success ?? commonSuccess,
})

export const additionalPremiumActivities: PremiumActivity[] = [
  activity({slug:'secuencia-cuento',title:'Ordenamos el cuento',subject:'Lenguaje',level:'2.º básico',oa:'OA 5',format:'Secuencia visual',duration:'25 min',illustration:'reading',summary:'Ordena acciones, reconoce inicio, desarrollo y final, y relata usando conectores.',goal:'Comprender la secuencia temporal de un relato.',content:{type:'sequence',title:'La semilla viajera',body:'Una semilla vuela, cae en la tierra, recibe agua y se transforma en una planta.',items:['La semilla vuela','Cae en la tierra','Recibe agua','Crece una planta']}}),
  activity({slug:'personajes-ambiente',title:'Personajes y ambientes',subject:'Lenguaje',level:'3.º básico',oa:'OA 4',format:'Guía interactiva',duration:'30 min',illustration:'forest',summary:'Identifica personajes, características y ambientes mediante pistas textuales.',goal:'Reconocer información explícita y describir elementos narrativos.',content:{type:'text',title:'Una tarde en la laguna',body:'Camila y Tomás caminaron junto a una laguna tranquila. Observaron patos, juncos y montañas reflejadas en el agua.',items:['¿Quiénes participan?','¿Dónde ocurre?','Describe el ambiente.']}}),
  activity({slug:'vocabulario-contexto',title:'Palabras detectives',subject:'Lenguaje',level:'4.º básico',oa:'OA 10',format:'Juego de vocabulario',duration:'25 min',illustration:'reading',summary:'Descubre el significado de palabras nuevas usando contexto, prefijos y ejemplos.',goal:'Inferir significados a partir del contexto.',content:{type:'text',title:'La palabra misteriosa',body:'El sendero era estrecho: apenas permitía que una persona avanzara a la vez.',items:['¿Qué significa estrecho?','¿Qué pista ayuda?','Escribe un sinónimo.']}}),
  activity({slug:'idea-principal',title:'Cazadores de la idea principal',subject:'Lenguaje',level:'5.º básico',oa:'OA 6',format:'Texto informativo',duration:'35 min',illustration:'reading',summary:'Distingue idea principal, detalles y propósito en textos informativos breves.',goal:'Sintetizar información relevante.',content:{type:'text',title:'El pudú',body:'El pudú es uno de los ciervos más pequeños del mundo. Habita bosques del sur de Chile y se alimenta de hojas, frutos y brotes.',items:['Idea principal','Dos detalles','Propósito del texto']}}),
  activity({slug:'poesia-versos-estrofas',title:'Exploradores de poesía',subject:'Lenguaje',level:'3.º básico',oa:'OA 5',format:'Ficha lúdica',duration:'25 min',illustration:'reading',summary:'Reconoce versos, estrofas, rimas y emociones en poemas breves.',goal:'Comprender la estructura básica de un poema.',content:{type:'text',title:'La luna curiosa',body:'La luna mira el río,\ncon su vestido de plata,\ny cada pez que la observa,\ncon una burbuja la saluda.',items:['Cuenta versos','Identifica la estrofa','Busca palabras que riman']}}),
  activity({slug:'escritura-planificada',title:'Mi historia en cinco pasos',subject:'Lenguaje',level:'4.º básico',oa:'OA 17',format:'Taller de escritura',duration:'45 min',illustration:'letterm',summary:'Planifica, redacta, revisa y mejora una narración usando organizadores.',goal:'Escribir una narración coherente.',content:{type:'writing',title:'Una aventura inesperada',body:'Completa personaje, lugar, problema, solución y final.',items:['Personaje','Ambiente','Problema','Solución','Final']}}),
  activity({slug:'comprension-instrucciones',title:'Sigo instrucciones paso a paso',subject:'Lenguaje',level:'1.º–3.º básico',oa:'Comprensión',format:'Entrenamiento DUA',duration:'20 min',illustration:'routine',summary:'Comprende instrucciones breves mediante secuencias, pictogramas y comprobación.',goal:'Ejecutar instrucciones de dos y tres pasos.',content:{type:'sequence',title:'Prepara tu trabajo',body:'Observa, ordena y realiza la secuencia.',items:['Busca el lápiz','Escribe tu nombre','Marca la respuesta','Revisa']}}),
  activity({slug:'sumas-reserva',title:'Puentes de suma con reserva',subject:'Matemática',level:'3.º básico',oa:'OA 6',format:'Tutor guiado',duration:'30 min',illustration:'placevalue',summary:'Resuelve adiciones con reserva usando bloques, tabla posicional y algoritmo.',goal:'Comprender el reagrupamiento en la adición.',content:{type:'math',title:'Resuelve 268 + 157',body:'Representa, reagrupa y calcula.',items:['8 + 7 = 15','Escribe 5 y reserva 1','6 + 5 + 1','Comprueba el resultado']}}),
  activity({slug:'restas-reserva',title:'Misión resta con canje',subject:'Matemática',level:'3.º básico',oa:'OA 6',format:'Manipulativo',duration:'30 min',illustration:'placevalue',summary:'Comprende la sustracción con canje mediante material base diez.',goal:'Resolver restas con reserva explicando el canje.',content:{type:'math',title:'Resuelve 402 − 178',body:'Realiza los canjes necesarios antes de restar.',items:['Canjea una centena','Forma decenas','Canjea una decena','Comprueba sumando']}}),
  activity({slug:'fracciones-pizza',title:'Pizzería de fracciones',subject:'Matemática',level:'4.º básico',oa:'OA 8',format:'Manipulativo visual',duration:'35 min',illustration:'market',summary:'Representa, compara y construye fracciones propias con modelos circulares.',goal:'Comprender fracción como parte de un todo.',content:{type:'math',title:'Prepara las pizzas',body:'Divide y representa las fracciones solicitadas.',items:['1/2','2/4','3/4','¿Cuáles son equivalentes?']}}),
  activity({slug:'perimetro-area',title:'Arquitectos del patio escolar',subject:'Matemática',level:'4.º básico',oa:'OA 21',format:'Desafío aplicado',duration:'40 min',illustration:'placevalue',summary:'Calcula perímetro y área diseñando espacios del patio escolar.',goal:'Diferenciar y calcular perímetro y área.',content:{type:'math',title:'Diseña un huerto',body:'El huerto mide 8 m de largo y 5 m de ancho.',items:['Calcula perímetro','Calcula área','Dibuja otra figura con igual área']}}),
  activity({slug:'decimales-posicional',title:'Laboratorio decimal',subject:'Matemática',level:'5.º básico',oa:'OA 10',format:'Exploración guiada',duration:'35 min',illustration:'placevalue',summary:'Lee, representa y compara décimos y centésimos usando cuadrículas y dinero.',goal:'Comprender valor posicional decimal.',content:{type:'math',title:'Representa 3,47',body:'Ubica unidades, décimos y centésimos.',items:['3 unidades','4 décimos','7 centésimos','Compara con 3,5']}}),
  activity({slug:'tablas-6-7',title:'Desafío relámpago tablas 6 y 7',subject:'Matemática',level:'3.º–4.º básico',oa:'OA 7',format:'Juego',duration:'20 min',illustration:'puzzle',summary:'Practica tablas del 6 y 7 con patrones, asociaciones y retos graduados.',goal:'Automatizar multiplicaciones manteniendo comprensión.',content:{type:'math',title:'Completa el tablero',body:'Resuelve y explica una estrategia.',items:['6×8','7×6','6×9','7×8']}}),
  activity({slug:'problemas-multiplicativos',title:'Agencia de problemas',subject:'Matemática',level:'5.º básico',oa:'OA 4',format:'Resolución de problemas',duration:'40 min',illustration:'market',summary:'Selecciona datos, operación y estrategia en problemas multiplicativos.',goal:'Resolver problemas y justificar procedimientos.',content:{type:'math',title:'Excursión escolar',body:'Viajan 7 cursos con 36 estudiantes cada uno.',items:['¿Cuántos viajan?','Estima primero','Calcula exactamente','Explica tu estrategia']}}),
  activity({slug:'sistema-solar',title:'Viaje por el sistema solar',subject:'Ciencias',level:'3.º básico',oa:'OA 11',format:'Exploración visual',duration:'40 min',illustration:'ecosystem',summary:'Ordena planetas, compara características y explica movimientos básicos.',goal:'Reconocer componentes del sistema solar.',content:{type:'science',title:'Nuestra vecindad espacial',body:'Explora el Sol, los planetas y sus posiciones.',items:['Sol','Tierra','Luna','Planetas interiores','Planetas exteriores']}}),
  activity({slug:'ciclo-agua',title:'La aventura de una gota',subject:'Ciencias',level:'2.º–4.º básico',oa:'OA 12',format:'Secuencia animada',duration:'30 min',illustration:'ecosystem',summary:'Explica evaporación, condensación, precipitación y acumulación.',goal:'Comprender el ciclo del agua.',content:{type:'sequence',title:'El viaje de Gotita',body:'Ordena las etapas del ciclo.',items:['Evaporación','Condensación','Precipitación','Acumulación']}}),
  activity({slug:'cuerpo-humano',title:'Estaciones del cuerpo humano',subject:'Ciencias',level:'5.º básico',oa:'OA 6',format:'Circuito de aprendizaje',duration:'45 min',illustration:'circuit',summary:'Relaciona sistemas digestivo, respiratorio y circulatorio con hábitos saludables.',goal:'Comprender funciones integradas del organismo.',content:{type:'science',title:'Sistemas que trabajan juntos',body:'Relaciona órganos, funciones y cuidados.',items:['Pulmones','Corazón','Estómago','Intestinos','Hábitos saludables']}}),
  activity({slug:'humo-cigarrillo',title:'Aire limpio, cuerpo protegido',subject:'Ciencias',level:'5.º básico',oa:'OA 7',format:'Texto + preguntas',duration:'35 min',illustration:'science',summary:'Analiza componentes del cigarrillo y efectos del humo directo e indirecto.',goal:'Explicar consecuencias del tabaco en la salud.',content:{type:'science',title:'¿Qué contiene el humo?',body:'El humo del cigarrillo contiene sustancias tóxicas que dañan pulmones, corazón y otros órganos.',items:['Nicotina','Alquitrán','Monóxido de carbono','Humo de segunda mano']}}),
  activity({slug:'pueblos-originarios',title:'Voces de los pueblos originarios',subject:'Historia',level:'2.º–4.º básico',oa:'OA 1',format:'Galería interactiva',duration:'40 min',illustration:'routine',summary:'Reconoce diversidad cultural, territorios y aportes de pueblos originarios de Chile.',goal:'Valorar diversidad y continuidad cultural.',content:{type:'text',title:'Diversidad de Chile',body:'Los pueblos originarios poseen lenguas, conocimientos, tradiciones y formas de relacionarse con la naturaleza.',items:['Mapuche','Aymara','Rapa Nui','Selk’nam']}}),
  activity({slug:'roma-legado',title:'Museo del legado romano',subject:'Historia',level:'5.º básico',oa:'OA 3',format:'Tarjetas de estudio',duration:'35 min',illustration:'assessment',summary:'Explora Coliseo, Panteón, caminos, leyes y aportes romanos.',goal:'Explicar elementos del legado romano vigentes.',content:{type:'text',title:'Roma permanece',body:'El legado romano se observa en arquitectura, derecho, idioma, caminos y organización urbana.',items:['Coliseo','Panteón','Derecho romano','Lenguas romances','Caminos']}}),
  activity({slug:'conquista-america',title:'Rutas de la conquista de América',subject:'Historia',level:'5.º básico',oa:'OA 2',format:'Línea de tiempo',duration:'45 min',illustration:'reading',summary:'Organiza causas, viajes, conquista y consecuencias con enfoque comprensible.',goal:'Comprender el proceso de conquista y sus consecuencias.',content:{type:'sequence',title:'Del viaje a la conquista',body:'Ordena hechos y analiza distintos impactos.',items:['Búsqueda de rutas','Llegada a América','Conquista de imperios','Llegada a Chile','Consecuencias']}}),
  activity({slug:'emociones-semaforo',title:'Semáforo de emociones',subject:'Orientación',level:'1.º–6.º básico',oa:'Convivencia',format:'Tablero de autorregulación',duration:'Uso diario',illustration:'routine',summary:'Identifica intensidad emocional y selecciona estrategias de regulación.',goal:'Reconocer emociones y pedir apoyo oportunamente.',content:{type:'sequence',title:'Paro, respiro y elijo',body:'Utiliza el semáforo antes de actuar.',items:['Rojo: me detengo','Amarillo: respiro','Verde: elijo una estrategia']}}),
  activity({slug:'amistad-convivencia',title:'Puentes de amistad',subject:'Orientación',level:'3.º–5.º básico',oa:'Convivencia',format:'Juego colaborativo',duration:'30 min',illustration:'puzzle',summary:'Practica escucha, empatía, resolución de conflictos y acuerdos.',goal:'Fortalecer habilidades de convivencia.',content:{type:'text',title:'Resolver juntos',body:'Dos compañeros quieren usar el mismo material al mismo tiempo.',items:['¿Qué siente cada uno?','Propón dos soluciones','Elijan un acuerdo justo']}}),
  activity({slug:'evaluacion-tablas-diversificada',title:'Evaluación diversificada de multiplicación',subject:'Evaluación',level:'3.º–4.º básico',oa:'OA 7',format:'TDA / DIL',duration:'40 min',illustration:'assessment',summary:'Evalúa tablas y problemas simples con versiones equivalentes y apoyos visuales.',goal:'Evaluar comprensión multiplicativa de manera accesible.',content:{type:'math',title:'Demuestro lo aprendido',body:'Resuelve operaciones, asociaciones y un problema.',items:['Selección múltiple','Une operación y resultado','Completa patrón','Problema breve']}}),
  activity({slug:'ticket-salida-universal',title:'Ticket de salida universal',subject:'Evaluación',level:'Multinivel',oa:'Evaluación formativa',format:'Plantilla editable',duration:'5 min',illustration:'assessment',summary:'Cierre rápido con aprendizaje, dificultad, estrategia y nivel de confianza.',goal:'Recoger evidencia formativa al finalizar una clase.',content:{type:'writing',title:'Antes de salir',body:'Responde de forma escrita, oral o señalada.',items:['Hoy aprendí…','Todavía necesito ayuda en…','La estrategia que usé fue…','Mi confianza es…']}}),
]
