import type { PremiumActivity } from './premiumActivities'

export const additionalActivities2: PremiumActivity[] = [
  {
    slug: 'vocales-sonidos', title: 'Exploradores de vocales', subject: 'Lectoescritura', level: 'Kínder–1.º básico', oa: 'OA 3', format: 'Juego fonológico', duration: '20 min', illustration: 'letterm',
    summary: 'Reconocimiento auditivo y visual de vocales mediante imágenes, sonidos y clasificación.',
    goal: 'Identificar vocales iniciales en palabras de uso frecuente.',
    steps: ['Escuchar una palabra.', 'Identificar el sonido inicial.', 'Elegir la vocal.', 'Relacionar con una imagen.', 'Trazar la letra.'],
    supports: ['Audio lento', 'Imágenes grandes', 'Trazo guiado', 'Dos opciones', 'Respuesta señalada'],
    success: ['Reconoce el sonido inicial.', 'Relaciona vocal e imagen.', 'Traza siguiendo dirección.'],
    content: { type: 'writing', title: '¿Con qué vocal comienza?', body: 'Escucha y relaciona cada palabra con su vocal inicial.', items: ['A de avión', 'E de elefante', 'I de isla', 'O de oso', 'U de uva'] },
  },
  {
    slug: 'familias-silabicas', title: 'Tren de sílabas M, P, L, S y T', subject: 'Lectoescritura', level: '1.º básico', oa: 'OA 4', format: 'Juego + ficha', duration: '30 min', illustration: 'letterm',
    summary: 'Construcción de sílabas y palabras con consonantes iniciales de alta frecuencia.',
    goal: 'Leer y formar sílabas directas y palabras simples.',
    steps: ['Escuchar el fonema.', 'Combinar con vocales.', 'Leer la sílaba.', 'Formar una palabra.', 'Completar una oración.'],
    supports: ['Marcado silábico', 'Audio', 'Letras móviles', 'Pictogramas', 'Lectura compartida'],
    success: ['Lee sílabas directas.', 'Forma palabras.', 'Comprende una oración breve.'],
    content: { type: 'writing', title: 'El tren de las palabras', body: 'Une consonante y vocal para formar sílabas.', items: ['ma me mi mo mu', 'pa pe pi po pu', 'la le li lo lu', 'sa se si so su', 'ta te ti to tu'] },
  },
  {
    slug: 'tablas-6-7-desafio', title: 'Desafío de las tablas del 6 y 7', subject: 'Matemática', level: '3.º–4.º básico', oa: 'OA 7', format: 'Juego por niveles', duration: '25 min', illustration: 'puzzle',
    summary: 'Práctica de multiplicaciones con patrones, series, tarjetas y desafíos de rapidez sin penalizar el error.',
    goal: 'Automatizar las tablas del 6 y 7 usando estrategias y patrones.',
    steps: ['Completar series.', 'Relacionar operación y resultado.', 'Resolver tarjetas.', 'Explicar un patrón.', 'Superar el desafío final.'],
    supports: ['Tabla visible', 'Modo sin tiempo', 'Menos ejercicios', 'Audio', 'Retroalimentación inmediata'],
    success: ['Resuelve con precisión.', 'Reconoce patrones.', 'Explica una estrategia.'],
    content: { type: 'math', title: 'Sube de nivel', body: 'Resuelve y observa cómo aumentan los resultados.', items: ['6×4=24', '6×7=42', '7×5=35', '7×8=56', '6×9=54'] },
  },
  {
    slug: 'decimales-valor-posicional', title: 'Laboratorio de números decimales', subject: 'Matemática', level: '5.º–6.º básico', oa: 'OA 7', format: 'Manipulativo digital', duration: '35 min', illustration: 'placevalue',
    summary: 'Lectura, escritura y representación de décimos y centésimos en cuadrículas y tabla posicional.',
    goal: 'Comprender el valor posicional de números decimales.',
    steps: ['Leer el número.', 'Ubicar parte entera y decimal.', 'Representar en cuadrícula.', 'Descomponer.', 'Comparar dos números.'],
    supports: ['Tabla posicional', 'Cuadrícula 10×10', 'Colores por posición', 'Audio', 'Ejemplo resuelto'],
    success: ['Lee correctamente.', 'Ubica décimos y centésimos.', 'Compara usando valor posicional.'],
    content: { type: 'math', title: 'Representa 3,47', body: 'Ubica cada cifra y escribe la descomposición.', items: ['3 unidades', '4 décimos', '7 centésimos', '3,47 = 3 + 0,4 + 0,07'] },
  },
  {
    slug: 'cigarrillo-salud', title: 'Respirar sin humo', subject: 'Ciencias', level: '5.º básico', oa: 'OA 7', format: 'Texto informativo + preguntas', duration: '35 min', illustration: 'circuit',
    summary: 'Información clara sobre componentes del cigarrillo y efectos en fumadores y personas expuestas al humo.',
    goal: 'Explicar consecuencias del cigarrillo en el organismo y el ambiente cercano.',
    steps: ['Leer el texto.', 'Identificar componentes.', 'Relacionar daño y órgano.', 'Analizar humo de segunda mano.', 'Proponer medidas de protección.'],
    supports: ['Texto segmentado', 'Glosario', 'Infografía', 'Lectura mediada', 'Respuesta en cuaderno'],
    success: ['Reconoce componentes dañinos.', 'Explica dos efectos.', 'Propone una acción preventiva.'],
    content: { type: 'science', title: '¿Qué contiene el humo?', body: 'El humo del cigarrillo contiene nicotina, alquitrán y monóxido de carbono, sustancias que afectan pulmones, corazón y circulación.', items: ['¿Qué órgano se afecta?', '¿Qué es el humo de segunda mano?', 'Escribe dos medidas de protección.'] },
  },
  {
    slug: 'autoevaluacion-dua', title: 'Mi forma de aprender', subject: 'PIE / DUA', level: 'Multinivel', oa: 'Metacognición', format: 'Autoevaluación visual', duration: '12 min', illustration: 'routine',
    summary: 'Herramienta para identificar apoyos útiles, nivel de autonomía y siguiente meta personal.',
    goal: 'Favorecer metacognición y participación en decisiones de apoyo.',
    steps: ['Elegir cómo me sentí.', 'Identificar qué apoyo ayudó.', 'Marcar autonomía.', 'Reconocer un logro.', 'Definir una meta.'],
    supports: ['Escala visual', 'Pictogramas', 'Respuesta oral', 'Texto simple', 'Lectura del adulto'],
    success: ['Reconoce un apoyo útil.', 'Describe un logro.', 'Define una meta alcanzable.'],
    content: { type: 'sequence', title: 'Hoy aprendí mejor cuando...', body: 'Selecciona la opción que mejor representa tu experiencia.', items: ['Vi un ejemplo', 'Escuché la explicación', 'Usé material concreto', 'Trabajé con un compañero', 'Tuve más tiempo'] },
  },
]
