import type { PremiumActivity } from './premiumActivities'

const base=(slug:string,title:string,subject:string,level:string,oa:string,format:string,duration:string,illustration:string,summary:string,goal:string,body:string,items:string[],supports:string[]):PremiumActivity=>({slug,title,subject,level,oa,format,duration,illustration,summary,goal,steps:['Activar conocimientos previos.','Modelar un ejemplo.','Resolver la actividad guiada.','Aplicar de manera autónoma.','Revisar y registrar el logro.'],supports,success:['Comprende la instrucción.','Aplica la habilidad central.','Explica o demuestra su respuesta.'],content:{type:subject==='Matemática'?'math':subject==='Ciencias'?'science':subject==='PIE / DUA'?'sequence':subject==='Lectoescritura'?'writing':'text',title,body,items}})

export const extraActivities:PremiumActivity[]=[
base('secuencia-cuento','Ordena el cuento perdido','Lenguaje','2.º básico','OA 5','Secuencia visual','25 min','reading','Ordenamiento de acciones con conectores temporales e imágenes.','Reconocer inicio, desarrollo y final.','Ordena las escenas y relata lo ocurrido.',['Primero','Luego','Después','Finalmente'],['Imágenes grandes','Lectura mediada','Respuesta oral','Menos alternativas']),
base('vocabulario-contexto','Exploradores de palabras','Lenguaje','4.º básico','OA 10','Juego lingüístico','30 min','forest','Descubrimiento del significado de palabras mediante pistas del contexto.','Inferir vocabulario nuevo.','Lee cada oración, subraya las pistas y explica la palabra.',['frondoso','agotado','silencioso','precavido'],['Glosario visual','Audio','Palabras destacadas','Trabajo en pareja']),
base('idea-principal','La idea más importante','Lenguaje','5.º básico','OA 6','Guía interactiva','35 min','reading','Diferenciación entre tema, idea principal y detalles.','Sintetizar información de un texto.','Lee el texto y selecciona la oración que resume mejor su contenido.',['Tema','Idea principal','Detalle 1','Detalle 2'],['Texto fragmentado','Marcador visual','Lectura en voz alta','Respuesta oral']),
base('poesia-versos','Taller de versos y estrofas','Lenguaje','3.º básico','OA 5','Ficha lúdica','25 min','reading','Reconocimiento de versos, estrofas, rimas y lenguaje figurado sencillo.','Analizar la estructura de un poema.','Marca versos y estrofas; encuentra palabras que riman.',['Versos','Estrofas','Rima','Título'],['Letra ampliada','Código visual','Lectura coral','Ejemplo resuelto']),
base('noticia-escolar','Reporteros del colegio','Lenguaje','6.º básico','OA 15','Proyecto breve','45 min','assessment','Producción de una noticia con titular, entrada y cuerpo.','Escribir para informar con claridad.','Redacta una noticia sobre una actividad escolar.',['Titular','Qué ocurrió','Cuándo y dónde','Fuente'],['Plantilla estructurada','Banco de conectores','Dictado por voz','Lista de cotejo']),
base('sumas-reserva','Estación de sumas con reserva','Matemática','3.º básico','OA 6','Tutor guiado','30 min','placevalue','Sumas de dos y tres cifras con representación concreta y algoritmo.','Comprender el canje en la adición.','Resuelve 268 + 157 usando bloques y algoritmo.',['Unidades','Canje','Decenas','Resultado'],['Bloques base diez','Cuadrícula','Colores por posición','Ejemplo paso a paso']),
base('restas-reserva','Puente de las restas','Matemática','3.º básico','OA 7','Tutor guiado','30 min','placevalue','Sustracciones con descomposición y comprobación.','Aplicar el algoritmo comprendiendo el préstamo.','Resuelve 402 - 178 y comprueba con una suma.',['Descomponer','Restar','Reagrupar','Comprobar'],['Material concreto','Cuadrícula','Narración de pasos','Menos ejercicios']),
base('fracciones-pizza','Pizzería de fracciones','Matemática','4.º básico','OA 8','Manipulativo','35 min','market','Representación y comparación de fracciones propias.','Relacionar fracción con parte de un todo.','Construye pizzas y compara porciones.',['1/2','1/3','2/4','3/4'],['Piezas recortables','Colores contrastantes','Lectura de fracciones','Respuesta manipulativa']),
base('perimetro-area','Arquitectos del patio','Matemática','4.º básico','OA 21','Desafío aplicado','40 min','placevalue','Cálculo de perímetro y área en planos cuadriculados.','Distinguir y calcular perímetro y área.','Diseña un patio rectangular y calcula sus medidas.',['Largo','Ancho','Perímetro','Área'],['Cuadrícula grande','Fórmulas visibles','Material concreto','Calculadora autorizable']),
base('decimales-posicional','Laboratorio decimal','Matemática','6.º básico','OA 7','Manipulativo digital','35 min','placevalue','Lectura, escritura y valor posicional de números decimales.','Representar décimos y centésimos.','Representa 3,47 y explica el valor de cada cifra.',['Unidades','Décimos','Centésimos','Descomposición'],['Tabla posicional','Cuadrícula decimal','Audio','Ejemplo resuelto']),
base('probabilidad-dados','Casino matemático seguro','Matemática','6.º básico','OA 24','Simulación','40 min','puzzle','Experimentos aleatorios, frecuencia y probabilidad simple.','Estimar y calcular probabilidades.','Lanza dos dados virtuales y registra resultados.',['Evento posible','Frecuencia','Probabilidad','Conclusión'],['Tabla automática','Ensayos reducidos','Gráfico visual','Trabajo colaborativo']),
base('geometria-angulos','Detectives de ángulos','Matemática','5.º básico','OA 18','Caza visual','30 min','puzzle','Identificación y medición de ángulos en objetos cotidianos.','Clasificar ángulos agudos, rectos y obtusos.','Busca ángulos en la sala y clasifícalos.',['Agudo','Recto','Obtuso','Extendido'],['Transportador visual','Modelos reales','Tarjetas de apoyo','Respuesta señalada']),
base('sistema-solar','Viaje por el sistema solar','Ciencias','3.º básico','OA 11','Exploración interactiva','35 min','ecosystem','Planetas, movimientos y características principales.','Describir componentes del sistema solar.','Ordena los planetas y compara dos de ellos.',['Sol','Planetas rocosos','Planetas gaseosos','Órbitas'],['Animación lenta','Audio','Tarjetas visuales','Glosario']),
base('ciclo-agua','La misión de una gota','Ciencias','2.º básico','OA 11','Secuencia animada','30 min','ecosystem','Ciclo del agua mediante una historia visual.','Explicar evaporación, condensación y precipitación.','Acompaña a una gota y ordena sus cambios.',['Evaporación','Condensación','Precipitación','Acumulación'],['Pictogramas','Relato oral','Flechas grandes','Respuesta por ordenamiento']),
base('cuerpo-humano','Equipo del cuerpo humano','Ciencias','5.º básico','OA 6','Mapa corporal','40 min','ecosystem','Relación entre sistemas digestivo, respiratorio y circulatorio.','Comprender el trabajo coordinado de los sistemas.','Ubica órganos y explica cómo colaboran.',['Pulmones','Corazón','Estómago','Intestinos'],['Silueta ampliada','Etiquetas móviles','Audio','Texto simplificado']),
base('cigarrillo-salud','Decisiones que cuidan la salud','Ciencias','5.º básico','OA 6','Texto + casos','35 min','assessment','Consecuencias del cigarrillo y exposición al humo.','Explicar daños y tomar decisiones de autocuidado.','Analiza situaciones y propone una respuesta saludable.',['Nicotina','Alquitrán','Humo ambiental','Prevención'],['Lenguaje claro','Infografía','Lectura mediada','Respuesta oral']),
base('romanos-legado','Ruta del legado romano','Historia','5.º básico','OA 3','Tarjetas de estudio','35 min','forest','Coliseo, Panteón y aportes romanos a la actualidad.','Reconocer continuidad histórica.','Relaciona monumentos y legados con ejemplos actuales.',['Coliseo','Panteón','Derecho','Arquitectura'],['Tarjetas visuales','Línea de tiempo','Audio','Preguntas breves']),
base('conquista-america','Voces de la conquista','Historia','5.º básico','OA 2','Línea de tiempo','40 min','forest','Viajes, conquista y consecuencias desde distintas perspectivas.','Ordenar hechos y reconocer consecuencias.','Completa la línea de tiempo y compara experiencias.',['Viajes','Imperios','Chile','Consecuencias'],['Mapa visual','Textos breves','Lectura compartida','Banco de palabras']),
base('chile-zonas','Chile de norte a sur','Historia','3.º básico','OA 8','Mapa interactivo','35 min','forest','Zonas naturales, clima, relieve y actividades humanas.','Caracterizar zonas de Chile.','Ubica cada zona y asocia una característica.',['Norte','Centro','Sur','Austral'],['Mapa grande','Íconos','Audio','Arrastrar y soltar']),
base('emociones-semaforo','Semáforo de autorregulación','PIE / DUA','Multinivel','Convivencia','Tablero interactivo','Uso diario','routine','Identificación de emociones y estrategias para volver a la calma.','Favorecer autorregulación y petición de ayuda.','Selecciona tu estado y una estrategia de apoyo.',['Verde: preparado','Amarillo: necesito pausa','Rojo: necesito ayuda','Plan de regreso'],['Pictogramas','Lectura fácil','Audio','Elección sin escritura']),
base('instrucciones-pasos','Comprendo instrucciones','PIE / DUA','1.º–4.º básico','Acceso','Entrenamiento visual','20 min','routine','Práctica de instrucciones de uno a cuatro pasos.','Mejorar comprensión y memoria de trabajo.','Escucha, repite y ejecuta la secuencia.',['Mira','Toma','Ordena','Revisa'],['Una instrucción por vez','Apoyo gestual','Repetición','Temporizador visual']),
base('funciones-ejecutivas','Misión: organizarme','PIE / DUA','3.º–6.º básico','Acceso','Planificador visual','Uso diario','routine','Organización de materiales, tiempo y tareas.','Fortalecer planificación y autonomía.','Organiza una tarea escolar en pasos y verifica avances.',['Qué haré','Qué necesito','Cuánto tiempo','Cómo revisaré'],['Checklist visual','Alertas','Pausa programada','Modelado']),
base('comunicacion-familia','Bitácora positiva para familias','PIE / DUA','Multinivel','Comunicación','Plantilla editable','15 min','assessment','Registro breve de avances, apoyos y acuerdos escuela-hogar.','Comunicar en lenguaje positivo y accionable.','Completa un mensaje de avance con una sugerencia concreta.',['Fortaleza observada','Avance','Apoyo útil','Acuerdo'],['Frases sugeridas','Lenguaje respetuoso','Formato breve','Lectura fácil']),
base('evaluacion-tablas','Evaluación lúdica tablas 6 y 7','Evaluación','3.º–4.º básico','OA 7','Juego evaluativo','35 min','puzzle','Ítems variados de asociación, completación y desafío final.','Evaluar dominio de tablas 6 y 7.','Resuelve retos y registra estrategias.',['6×8','7×6','Completa la serie','Explica una estrategia'],['Tabla visible opcional','Modo sin tiempo','Menos ítems','Lectura de instrucciones'])
]
