import type { PremiumActivity } from './premiumActivities'

type Seed = Omit<PremiumActivity,'steps'|'supports'|'success'> & Partial<Pick<PremiumActivity,'steps'|'supports'|'success'>>

const activity=(seed:Seed):PremiumActivity=>({
 ...seed,
 steps:seed.steps??['Activar el desafío y comunicar la meta.','Explorar un ejemplo modelado.','Resolver una misión guiada.','Aplicar la habilidad en un reto nuevo.','Registrar evidencia y reflexionar.'],
 supports:seed.supports??['Instrucciones segmentadas','Modelado visual','Respuesta multimodal','Tiempo flexible','Retroalimentación inmediata'],
 success:seed.success??['Comprende el propósito.','Aplica la estrategia adecuada.','Explica o demuestra su aprendizaje.']
})

export const premiumExpansion2026:PremiumActivity[]=[
activity({slug:'escape-room-comprension',title:'Escape room: El misterio de la biblioteca',subject:'Lenguaje',level:'3.º–4.º básico',oa:'OA 4 y OA 6',format:'Escape room',duration:'45 min',illustration:'reading',summary:'Cinco enigmas narrativos con pistas explícitas, inferencias, vocabulario y secuencias para abrir el cofre final.',goal:'Integrar habilidades de comprensión lectora en una experiencia colaborativa.',supports:['Lectura mediada','Pistas graduadas','Audio opcional','Texto ampliado','Roles de equipo'],success:['Localiza información relevante.','Formula inferencias coherentes.','Coopera y justifica decisiones.'],content:{type:'text',title:'El libro que desapareció',body:'Cada sala entrega una clave. Lee, conversa, decide y registra la evidencia antes de avanzar.',items:['Clave de personajes','Clave de ambiente','Clave de inferencia','Clave de vocabulario','Código final']}}),
activity({slug:'noticiero-lector',title:'Noticiero lector del curso',subject:'Lenguaje',level:'4.º–6.º básico',oa:'OA 6 y OA 28',format:'Proyecto multimedia',duration:'3 clases',illustration:'reading',summary:'Los estudiantes investigan, sintetizan y presentan una noticia escolar en formato escrito, oral o audiovisual.',goal:'Comprender textos informativos y comunicar información con claridad.',content:{type:'writing',title:'Nuestra noticia',body:'Selecciona un hecho real del curso, organiza datos y crea un noticiero breve.',items:['Titular','Qué ocurrió','Quiénes participaron','Cuándo y dónde','Cierre audiovisual']}}),
activity({slug:'club-lectura-eleccion',title:'Club de lectura con rutas de elección',subject:'Lenguaje',level:'3.º–6.º básico',oa:'Lectura autónoma',format:'Ruta adaptativa',duration:'4 semanas',illustration:'reading',summary:'Plan lector con elecciones, metas personales, diario de lectura y encuentros breves de conversación literaria.',goal:'Fortalecer motivación, autonomía y comprensión profunda.',supports:['Textos por nivel','Audiolibro','Respuesta gráfica','Metas ajustables','Preguntas graduadas'],content:{type:'text',title:'Mi ruta lectora',body:'Elige un texto, define una meta y registra tus descubrimientos.',items:['Antes de leer','Durante la lectura','Palabra nueva','Conexión personal','Recomendación final']}}),
activity({slug:'comic-dialogos',title:'Taller de cómic y diálogos',subject:'Lenguaje',level:'2.º–5.º básico',oa:'OA 17',format:'Creador visual',duration:'50 min',illustration:'letterm',summary:'Construcción de historietas con personajes, globos de diálogo, secuencia y revisión guiada.',goal:'Escribir narraciones breves coherentes usando recursos visuales.',content:{type:'writing',title:'Una aventura en seis viñetas',body:'Diseña una historia con inicio, problema, solución y cierre.',items:['Personajes','Escenario','Diálogo','Onomatopeya','Revisión','Publicación']}}),
activity({slug:'laboratorio-ortografia',title:'Laboratorio de ortografía inteligente',subject:'Lenguaje',level:'3.º–6.º básico',oa:'Escritura',format:'Juego adaptativo',duration:'25 min',illustration:'letterm',summary:'Misiones breves de acentuación, uso de b/v, c/s/z y puntuación con retroalimentación explicada.',goal:'Aplicar reglas ortográficas en contexto y corregir errores conscientemente.',content:{type:'writing',title:'Repara el mensaje',body:'Detecta, corrige y explica cada cambio.',items:['Tildes','Mayúsculas','Puntuación','b/v','c/s/z']}}),
activity({slug:'radio-escolar',title:'Podcast: voces del aula',subject:'Lenguaje',level:'5.º–8.º básico',oa:'Comunicación oral',format:'Proyecto de audio',duration:'3 clases',illustration:'reading',summary:'Guion, grabación y publicación de un episodio breve sobre un tema curricular o de convivencia.',goal:'Planificar y producir un discurso oral claro, pertinente y creativo.',content:{type:'writing',title:'Episodio de cinco minutos',body:'Crea un guion con apertura, desarrollo, entrevista y cierre.',items:['Tema','Audiencia','Guion','Ensayo','Grabación','Autoevaluación']}}),
activity({slug:'mision-1000',title:'Misión 1.000: expedición numérica',subject:'Matemática',level:'3.º básico',oa:'OA 2 y OA 5',format:'Aventura por niveles',duration:'40 min',illustration:'placevalue',summary:'Retos progresivos de lectura, representación, composición, comparación y estimación de números.',goal:'Construir sentido numérico hasta 1.000.',content:{type:'math',title:'Cruza cinco estaciones',body:'Obtén una insignia en cada estación numérica.',items:['Representa','Descompone','Compara','Ordena','Estima']}}),
activity({slug:'tienda-fracciones',title:'Tienda de fracciones equivalentes',subject:'Matemática',level:'4.º–6.º básico',oa:'Fracciones',format:'Simulación',duration:'45 min',illustration:'market',summary:'Compra, combina y compara productos usando fracciones, equivalencias y representación visual.',goal:'Comprender equivalencias y comparación de fracciones en contexto.',content:{type:'math',title:'Completa los pedidos',body:'Selecciona porciones equivalentes y explica tu elección.',items:['1/2 y 2/4','3/6 y 1/2','2/3 y 4/6','Orden de fracciones']}}),
activity({slug:'detectives-del-error',title:'Detectives del error matemático',subject:'Matemática',level:'3.º–6.º básico',oa:'Resolución de problemas',format:'Análisis de errores',duration:'30 min',illustration:'division',summary:'Casos con procedimientos incorrectos para identificar, explicar y reparar errores frecuentes.',goal:'Desarrollar razonamiento matemático y metacognición.',content:{type:'math',title:'¿Dónde se equivocó?',body:'Analiza cada solución y propone una corrección.',items:['Error de cálculo','Error de operación','Error de valor posicional','Error de interpretación']}}),
activity({slug:'escape-room-geometria',title:'Escape room geométrico',subject:'Matemática',level:'4.º–6.º básico',oa:'Geometría',format:'Escape room',duration:'45 min',illustration:'puzzle',summary:'Desafíos de ángulos, polígonos, simetría, perímetro y área conectados por una historia.',goal:'Aplicar conceptos geométricos en problemas encadenados.',content:{type:'math',title:'La cámara secreta',body:'Resuelve las claves geométricas para abrir la cámara.',items:['Ángulos','Polígonos','Simetría','Perímetro','Área']}}),
activity({slug:'robot-algoritmos',title:'Programa al robot matemático',subject:'Matemática',level:'1.º–4.º básico',oa:'Patrones y orientación',format:'Programación sin pantalla',duration:'35 min',illustration:'circuit',summary:'Tablero de comandos para crear secuencias, reconocer patrones y resolver recorridos.',goal:'Desarrollar pensamiento lógico, planificación y orientación espacial.',supports:['Flechas grandes','Tablero manipulativo','Ensayo sin penalización','Parejas cooperativas'],content:{type:'sequence',title:'Lleva el robot a la meta',body:'Ordena comandos y comprueba el recorrido.',items:['Avanza','Gira','Repite','Evita obstáculo','Optimiza ruta']}}),
activity({slug:'feria-presupuesto',title:'Feria escolar con presupuesto',subject:'Matemática',level:'5.º–8.º básico',oa:'Números y operaciones',format:'Proyecto aplicado',duration:'3 clases',illustration:'market',summary:'Planificación de un puesto con costos, precios, ganancias, descuentos y registro financiero.',goal:'Aplicar operaciones y porcentajes en una situación auténtica.',content:{type:'math',title:'Diseña un puesto rentable',body:'Calcula inversión, precio de venta y ganancia esperada.',items:['Presupuesto','Costo unitario','Precio','Descuento','Ganancia']}}),
activity({slug:'ciencia-en-casa',title:'Laboratorio seguro: ciencia cotidiana',subject:'Ciencias',level:'2.º–6.º básico',oa:'Habilidades científicas',format:'Experimento guiado',duration:'40 min',illustration:'ecosystem',summary:'Experimentos seguros con materiales simples, predicción, observación y conclusión.',goal:'Aplicar el ciclo de indagación científica.',content:{type:'science',title:'Pregunta, prueba y explica',body:'Selecciona un experimento y registra cada etapa.',items:['Pregunta','Hipótesis','Materiales','Observaciones','Conclusión']}}),
activity({slug:'hospital-del-cuerpo',title:'Hospital del cuerpo humano',subject:'Ciencias',level:'5.º–6.º básico',oa:'Sistemas del cuerpo',format:'Simulación de casos',duration:'45 min',illustration:'circuit',summary:'Casos ficticios para relacionar síntomas, órganos, sistemas y hábitos saludables.',goal:'Explicar cómo los sistemas corporales trabajan de forma integrada.',content:{type:'science',title:'Resuelve el caso clínico escolar',body:'Analiza información, identifica el sistema y propone cuidados.',items:['Caso respiratorio','Caso circulatorio','Caso digestivo','Hábitos preventivos']}}),
activity({slug:'guardianes-biodiversidad',title:'Guardianes de la biodiversidad chilena',subject:'Ciencias',level:'3.º–6.º básico',oa:'Ecosistemas',format:'Proyecto STEAM',duration:'4 clases',illustration:'ecosystem',summary:'Investigación de una especie nativa, amenazas, diseño de solución y campaña de protección.',goal:'Comprender biodiversidad y proponer acciones de conservación.',content:{type:'science',title:'Protejamos una especie',body:'Investiga, diseña y comunica una solución.',items:['Especie','Hábitat','Amenaza','Prototipo','Campaña']}}),
activity({slug:'meteorologos-aula',title:'Estación meteorológica del aula',subject:'Ciencias',level:'2.º–5.º básico',oa:'Tiempo atmosférico',format:'Proyecto de datos',duration:'2 semanas',illustration:'ecosystem',summary:'Registro diario de temperatura, nubosidad, viento y precipitaciones con gráficos y predicciones.',goal:'Observar patrones del tiempo y comunicar datos.',content:{type:'science',title:'Nuestro informe del tiempo',body:'Registra datos, crea gráficos y formula una predicción.',items:['Temperatura','Nubosidad','Viento','Precipitación','Predicción']}}),
activity({slug:'museo-chile',title:'Museo vivo de Chile',subject:'Historia',level:'2.º–6.º básico',oa:'Historia y patrimonio',format:'Proyecto expositivo',duration:'4 clases',illustration:'assessment',summary:'Creación de salas temáticas con objetos, relatos, mapas, líneas de tiempo y mediación oral.',goal:'Valorar el patrimonio y comunicar aprendizajes históricos.',content:{type:'text',title:'Diseña una sala del museo',body:'Selecciona un tema y crea una experiencia para visitantes.',items:['Tema','Fuente histórica','Objeto','Texto de sala','Presentación oral']}}),
activity({slug:'cabildo-escolar',title:'Cabildo escolar: decidimos juntos',subject:'Historia',level:'4.º–8.º básico',oa:'Formación ciudadana',format:'Simulación cívica',duration:'45 min',illustration:'routine',summary:'Roles, propuestas, deliberación y votación sobre una necesidad real del curso.',goal:'Practicar participación, argumentación y toma democrática de decisiones.',content:{type:'text',title:'Una decisión para mejorar el curso',body:'Presenta una propuesta, escucha argumentos y vota informadamente.',items:['Problema','Propuesta','Argumentos','Acuerdo','Compromiso']}}),
activity({slug:'linea-tiempo-interactiva',title:'Constructor de líneas de tiempo',subject:'Historia',level:'3.º–8.º básico',oa:'Pensamiento temporal',format:'Herramienta interactiva',duration:'35 min',illustration:'reading',summary:'Ordena acontecimientos, calcula duración, identifica simultaneidad y explica cambios.',goal:'Desarrollar pensamiento cronológico y causal.',content:{type:'sequence',title:'Organiza el proceso histórico',body:'Ubica hechos y agrega relaciones de causa y consecuencia.',items:['Fecha','Acontecimiento','Duración','Causa','Consecuencia']}}),
activity({slug:'estudio-arte-chileno',title:'Estudio de arte chileno',subject:'Artes Visuales',level:'1.º–6.º básico',oa:'OA 1 y OA 3',format:'Taller creativo',duration:'60 min',illustration:'forest',summary:'Exploración de obras chilenas y creación personal con técnicas mixtas y opciones sensoriales.',goal:'Observar, expresar y crear a partir de referentes artísticos.',content:{type:'writing',title:'Mi obra y su historia',body:'Observa, selecciona materiales, crea y presenta tu obra.',items:['Observar','Elegir técnica','Crear','Nombrar obra','Compartir']}}),
activity({slug:'orquesta-corporal',title:'Orquesta corporal inclusiva',subject:'Música',level:'1.º–6.º básico',oa:'Interpretar y crear',format:'Experiencia sonora',duration:'35 min',illustration:'routine',summary:'Patrones rítmicos con cuerpo, instrumentos simples y apoyos visuales de intensidad y tempo.',goal:'Interpretar y crear secuencias rítmicas colaborativas.',supports:['Tarjetas rítmicas','Volumen regulable','Participación por elección','Modelado corporal','Pausa sensorial'],content:{type:'sequence',title:'Creamos una pieza rítmica',body:'Combina sonidos y silencios en cuatro secciones.',items:['Pulso','Patrón','Silencio','Cambio de intensidad','Presentación']}}),
activity({slug:'circuito-motor-aventura',title:'Circuito motor: expedición aventura',subject:'Educación Física',level:'Kínder–4.º básico',oa:'Habilidades motrices',format:'Circuito por estaciones',duration:'40 min',illustration:'tracing',summary:'Estaciones de equilibrio, coordinación, lanzamiento y desplazamiento con niveles ajustables.',goal:'Desarrollar habilidades motrices básicas de forma segura y motivadora.',supports:['Tres niveles de dificultad','Señalética visual','Demostración previa','Pausas de regulación','Alternativas sin impacto'],content:{type:'sequence',title:'Completa la expedición',body:'Supera cada estación respetando tu propio nivel.',items:['Equilibrio','Salto','Lanzamiento','Zigzag','Respiración final']}}),
activity({slug:'kit-desregulacion',title:'Kit de autorregulación: vuelvo a estar disponible',subject:'PIE / DUA',level:'Multinivel',oa:'Acceso y bienestar',format:'Kit visual',duration:'Uso cotidiano',illustration:'routine',summary:'Secuencia de identificación, pausa, elección de estrategia, retorno gradual y registro positivo.',goal:'Favorecer regulación emocional y retorno seguro al aprendizaje.',supports:['Pictogramas','Escala emocional','Tarjetas de pausa','Opciones sensoriales','Lenguaje simple'],success:['Reconoce una señal corporal.','Elige una estrategia segura.','Retorna con apoyo decreciente.'],content:{type:'sequence',title:'Mi plan para volver',body:'Selecciona cómo te sientes y qué apoyo necesitas.',items:['Noto','Pido pausa','Elijo estrategia','Pruebo','Vuelvo']}}),
activity({slug:'estaciones-funciones-ejecutivas',title:'Estaciones de funciones ejecutivas',subject:'PIE / DUA',level:'2.º–8.º básico',oa:'Acceso',format:'Circuito cognitivo',duration:'35 min',illustration:'puzzle',summary:'Juegos breves para memoria de trabajo, control inhibitorio, flexibilidad y planificación.',goal:'Fortalecer procesos ejecutivos vinculados al aprendizaje.',content:{type:'sequence',title:'Entrena tu cerebro',body:'Completa cuatro estaciones y reconoce la estrategia que más te ayudó.',items:['Recuerda','Espera','Cambia regla','Planifica','Reflexiona']}}),
activity({slug:'evaluacion-universal',title:'Constructor de evaluación universal',subject:'Evaluación',level:'Multinivel',oa:'DUA',format:'Plantilla inteligente',duration:'45 min',illustration:'assessment',summary:'Diseño de evaluaciones con equivalencia curricular, opciones de respuesta, apoyos y rúbrica común.',goal:'Crear evaluaciones accesibles sin reducir la expectativa de aprendizaje.',content:{type:'writing',title:'Diseña tres rutas equivalentes',body:'Define evidencia, barrera, apoyo y criterio de logro.',items:['Objetivo','Evidencia','Ruta visual','Ruta oral','Ruta escrita','Rúbrica']}}),
activity({slug:'portafolio-evidencias',title:'Portafolio vivo de evidencias',subject:'Evaluación',level:'Multinivel',oa:'Seguimiento',format:'Portafolio digital',duration:'Uso continuo',illustration:'assessment',summary:'Registro de producciones, fotografías, audios, autoevaluaciones y progreso por objetivo.',goal:'Documentar aprendizaje auténtico y tomar decisiones pedagógicas.',content:{type:'writing',title:'Mi evidencia de aprendizaje',body:'Sube o describe una evidencia y explica qué demuestra.',items:['Objetivo','Evidencia','Apoyo utilizado','Reflexión','Próximo paso']}})
]
