import type { PremiumActivity } from './premiumActivities'

type Seed = Pick<PremiumActivity,'slug'|'title'|'subject'|'level'|'oa'|'format'|'duration'|'illustration'|'summary'|'goal'|'content'> & Partial<Pick<PremiumActivity,'steps'|'supports'|'success'>>

const make=(s:Seed):PremiumActivity=>({
 ...s,
 steps:s.steps??['Activar conocimientos previos.','Modelar un ejemplo.','Resolver con apoyo.','Aplicar de forma autónoma.','Revisar y cerrar.'],
 supports:s.supports??['Instrucciones breves','Apoyo visual','Respuesta oral o escrita','Tiempo adicional'],
 success:s.success??['Comprende la instrucción.','Aplica la habilidad.','Explica su respuesta.']
})

export const resourceExpansion:PremiumActivity[]=[
make({slug:'secuencia-cuento',title:'Ordenamos el cuento',subject:'Lenguaje',level:'2.º básico',oa:'OA 5',format:'Secuencia visual',duration:'25 min',illustration:'reading',summary:'Ordena acciones y reconoce inicio, desarrollo y final.',goal:'Comprender la secuencia temporal de un relato.',content:{type:'sequence',title:'La semilla viajera',body:'Ordena las escenas y relata lo ocurrido.',items:['La semilla vuela','Cae en la tierra','Recibe agua','Crece una planta']}}),
make({slug:'personajes-ambiente',title:'Personajes y ambientes',subject:'Lenguaje',level:'3.º básico',oa:'OA 4',format:'Guía interactiva',duration:'30 min',illustration:'forest',summary:'Reconoce personajes, características y ambientes.',goal:'Identificar información explícita de textos narrativos.',content:{type:'text',title:'Una tarde en la laguna',body:'Camila y Tomás caminaron junto a una laguna tranquila.',items:['¿Quiénes participan?','¿Dónde ocurre?','Describe el ambiente.']}}),
make({slug:'vocabulario-contexto',title:'Palabras detectives',subject:'Lenguaje',level:'4.º básico',oa:'OA 10',format:'Juego lingüístico',duration:'25 min',illustration:'reading',summary:'Descubre significados usando pistas del contexto.',goal:'Inferir el significado de palabras nuevas.',content:{type:'text',title:'La palabra misteriosa',body:'El sendero era estrecho: apenas permitía que una persona avanzara.',items:['¿Qué significa estrecho?','¿Qué pista ayuda?','Escribe un sinónimo.']}}),
make({slug:'idea-principal',title:'Cazadores de la idea principal',subject:'Lenguaje',level:'5.º básico',oa:'OA 6',format:'Texto informativo',duration:'35 min',illustration:'reading',summary:'Distingue idea principal, tema y detalles.',goal:'Sintetizar información relevante.',content:{type:'text',title:'El pudú',body:'El pudú es uno de los ciervos más pequeños del mundo.',items:['Idea principal','Dos detalles','Propósito del texto']}}),
make({slug:'poesia-versos-estrofas',title:'Exploradores de poesía',subject:'Lenguaje',level:'3.º básico',oa:'OA 5',format:'Ficha lúdica',duration:'25 min',illustration:'reading',summary:'Reconoce versos, estrofas y rimas.',goal:'Comprender la estructura básica de un poema.',content:{type:'text',title:'La luna curiosa',body:'La luna mira el río con su vestido de plata.',items:['Cuenta versos','Identifica estrofas','Busca una rima']}}),
make({slug:'escritura-planificada',title:'Mi historia en cinco pasos',subject:'Lenguaje',level:'4.º básico',oa:'OA 17',format:'Taller de escritura',duration:'45 min',illustration:'letterm',summary:'Planifica y redacta una narración coherente.',goal:'Escribir una historia con estructura clara.',content:{type:'writing',title:'Una aventura inesperada',body:'Completa personaje, ambiente, problema, solución y final.',items:['Personaje','Ambiente','Problema','Solución','Final']}}),
make({slug:'sumas-reserva',title:'Puentes de suma con reserva',subject:'Matemática',level:'3.º básico',oa:'OA 6',format:'Tutor guiado',duration:'30 min',illustration:'placevalue',summary:'Resuelve adiciones con reserva usando bloques y algoritmo.',goal:'Comprender el reagrupamiento en la adición.',content:{type:'math',title:'Resuelve 268 + 157',body:'Representa, reagrupa y calcula.',items:['Unidades','Reserva','Decenas','Resultado']}}),
make({slug:'restas-reserva',title:'Misión resta con canje',subject:'Matemática',level:'3.º básico',oa:'OA 6',format:'Manipulativo',duration:'30 min',illustration:'placevalue',summary:'Comprende la sustracción con canje.',goal:'Resolver restas con reserva explicando el procedimiento.',content:{type:'math',title:'Resuelve 402 − 178',body:'Realiza los canjes necesarios.',items:['Canjea una centena','Forma decenas','Resta','Comprueba']}}),
make({slug:'fracciones-pizza',title:'Pizzería de fracciones',subject:'Matemática',level:'4.º básico',oa:'OA 8',format:'Manipulativo visual',duration:'35 min',illustration:'market',summary:'Representa y compara fracciones propias.',goal:'Comprender la fracción como parte de un todo.',content:{type:'math',title:'Prepara las pizzas',body:'Representa las fracciones solicitadas.',items:['1/2','2/4','3/4','Fracciones equivalentes']}}),
make({slug:'perimetro-area',title:'Arquitectos del patio escolar',subject:'Matemática',level:'4.º básico',oa:'OA 21',format:'Desafío aplicado',duration:'40 min',illustration:'placevalue',summary:'Calcula perímetro y área en situaciones reales.',goal:'Diferenciar y calcular perímetro y área.',content:{type:'math',title:'Diseña un huerto',body:'El huerto mide 8 m de largo y 5 m de ancho.',items:['Perímetro','Área','Dibujo','Explicación']}}),
make({slug:'decimales-posicional',title:'Laboratorio decimal',subject:'Matemática',level:'5.º básico',oa:'OA 10',format:'Exploración guiada',duration:'35 min',illustration:'placevalue',summary:'Lee, representa y compara décimos y centésimos.',goal:'Comprender el valor posicional decimal.',content:{type:'math',title:'Representa 3,47',body:'Ubica unidades, décimos y centésimos.',items:['3 unidades','4 décimos','7 centésimos','Compara']}}),
make({slug:'tablas-6-7',title:'Desafío relámpago tablas 6 y 7',subject:'Matemática',level:'3.º–4.º básico',oa:'OA 7',format:'Juego',duration:'20 min',illustration:'puzzle',summary:'Practica tablas mediante patrones y retos.',goal:'Automatizar multiplicaciones con comprensión.',content:{type:'math',title:'Completa el tablero',body:'Resuelve y explica una estrategia.',items:['6×8','7×6','6×9','7×8']}}),
make({slug:'problemas-multiplicativos',title:'Agencia de problemas',subject:'Matemática',level:'5.º básico',oa:'OA 4',format:'Resolución de problemas',duration:'40 min',illustration:'market',summary:'Selecciona datos, operación y estrategia.',goal:'Resolver problemas multiplicativos y justificar.',content:{type:'math',title:'Excursión escolar',body:'Viajan 7 cursos con 36 estudiantes cada uno.',items:['Estima','Calcula','Comprueba','Explica']}}),
make({slug:'sistema-solar',title:'Viaje por el sistema solar',subject:'Ciencias',level:'3.º básico',oa:'OA 11',format:'Exploración visual',duration:'40 min',illustration:'ecosystem',summary:'Ordena planetas y compara características.',goal:'Reconocer componentes del sistema solar.',content:{type:'science',title:'Nuestra vecindad espacial',body:'Explora el Sol, los planetas y sus posiciones.',items:['Sol','Tierra','Luna','Planetas']}}),
make({slug:'ciclo-agua',title:'La aventura de una gota',subject:'Ciencias',level:'2.º–4.º básico',oa:'OA 12',format:'Secuencia animada',duration:'30 min',illustration:'ecosystem',summary:'Explica las etapas del ciclo del agua.',goal:'Comprender evaporación, condensación y precipitación.',content:{type:'sequence',title:'El viaje de Gotita',body:'Ordena las etapas del ciclo.',items:['Evaporación','Condensación','Precipitación','Acumulación']}}),
make({slug:'cuerpo-humano',title:'Estaciones del cuerpo humano',subject:'Ciencias',level:'5.º básico',oa:'OA 6',format:'Circuito de aprendizaje',duration:'45 min',illustration:'circuit',summary:'Relaciona sistemas y hábitos saludables.',goal:'Comprender funciones integradas del organismo.',content:{type:'science',title:'Sistemas que trabajan juntos',body:'Relaciona órganos, funciones y cuidados.',items:['Pulmones','Corazón','Estómago','Intestinos']}}),
make({slug:'humo-cigarrillo',title:'Aire limpio, cuerpo protegido',subject:'Ciencias',level:'5.º básico',oa:'OA 7',format:'Texto + preguntas',duration:'35 min',illustration:'assessment',summary:'Analiza componentes del cigarrillo y efectos del humo.',goal:'Explicar consecuencias del tabaco en la salud.',content:{type:'science',title:'¿Qué contiene el humo?',body:'El humo contiene sustancias tóxicas que dañan el organismo.',items:['Nicotina','Alquitrán','Monóxido','Humo ambiental']}}),
make({slug:'pueblos-originarios',title:'Voces de los pueblos originarios',subject:'Historia',level:'2.º–4.º básico',oa:'OA 1',format:'Galería interactiva',duration:'40 min',illustration:'routine',summary:'Reconoce diversidad cultural y territorial.',goal:'Valorar aportes de pueblos originarios de Chile.',content:{type:'text',title:'Diversidad de Chile',body:'Los pueblos originarios poseen lenguas, conocimientos y tradiciones.',items:['Mapuche','Aymara','Rapa Nui','Selk’nam']}}),
make({slug:'roma-legado',title:'Museo del legado romano',subject:'Historia',level:'5.º básico',oa:'OA 3',format:'Tarjetas de estudio',duration:'35 min',illustration:'assessment',summary:'Explora monumentos y aportes romanos.',goal:'Explicar elementos del legado romano vigentes.',content:{type:'text',title:'Roma permanece',body:'El legado romano se observa en arquitectura, derecho e idioma.',items:['Coliseo','Panteón','Derecho','Lenguas romances']}}),
make({slug:'conquista-america',title:'Rutas de la conquista de América',subject:'Historia',level:'5.º básico',oa:'OA 2',format:'Línea de tiempo',duration:'45 min',illustration:'reading',summary:'Organiza causas, viajes y consecuencias.',goal:'Comprender el proceso de conquista de América.',content:{type:'sequence',title:'Del viaje a la conquista',body:'Ordena hechos y analiza impactos.',items:['Rutas','Llegada','Conquista','Consecuencias']}}),
make({slug:'emociones-semaforo',title:'Semáforo de emociones',subject:'PIE / DUA',level:'Multinivel',oa:'Convivencia',format:'Tablero visual',duration:'Uso diario',illustration:'routine',summary:'Identifica emociones y selecciona estrategias.',goal:'Favorecer autorregulación y petición de ayuda.',content:{type:'sequence',title:'Paro, respiro y elijo',body:'Utiliza el semáforo antes de actuar.',items:['Rojo','Amarillo','Verde','Plan de apoyo']}}),
make({slug:'funciones-ejecutivas',title:'Misión: organizarme',subject:'PIE / DUA',level:'3.º–6.º básico',oa:'Acceso',format:'Planificador visual',duration:'Uso diario',illustration:'routine',summary:'Organiza materiales, tiempo y tareas.',goal:'Fortalecer planificación y autonomía.',content:{type:'sequence',title:'Organizo mi tarea',body:'Planifica una actividad escolar.',items:['Qué haré','Qué necesito','Cuánto tiempo','Cómo revisaré']}}),
make({slug:'amistad-convivencia',title:'Puentes de amistad',subject:'Orientación',level:'3.º–5.º básico',oa:'Convivencia',format:'Juego colaborativo',duration:'30 min',illustration:'puzzle',summary:'Practica empatía y resolución de conflictos.',goal:'Fortalecer habilidades de convivencia.',content:{type:'text',title:'Resolver juntos',body:'Dos compañeros quieren usar el mismo material.',items:['Emociones','Soluciones','Acuerdo','Reflexión']}}),
make({slug:'evaluacion-tablas-diversificada',title:'Evaluación diversificada de multiplicación',subject:'Evaluación',level:'3.º–4.º básico',oa:'OA 7',format:'TDA / DIL',duration:'40 min',illustration:'assessment',summary:'Evalúa tablas y problemas con apoyos visuales.',goal:'Evaluar comprensión multiplicativa de manera accesible.',content:{type:'math',title:'Demuestro lo aprendido',body:'Resuelve operaciones, asociaciones y un problema.',items:['Selección','Asociación','Patrón','Problema']}})
]
