import Link from 'next/link'
import {AppShell} from '@/components/AppShell'
import {ForestHeroArt,ActivityArtwork} from '@/components/dashboard/DashboardIllustrations'
import {Sparkles,BookOpen,ClipboardCheck,Gamepad2,CalendarDays,Music,Volume2,Trophy,Clock3,Users,Target,ChevronRight,Search} from 'lucide-react'
import {premiumActivities} from '@/lib/premiumActivities'

const recommended=premiumActivities.slice(0,5)
const artKinds=['reading','math','science','writing','forest']

function WelcomeTeacher(){return <svg className="welcome-teacher" viewBox="0 0 360 190" role="img" aria-label="Profesora saludando con libros">
 <defs><linearGradient id="shirt" x1="0" x2="1"><stop stopColor="#6f35de"/><stop offset="1" stopColor="#a05cf2"/></linearGradient><filter id="soft"><feDropShadow dx="0" dy="8" stdDeviation="8" floodOpacity=".16"/></filter></defs>
 <circle cx="260" cy="48" r="10" fill="#ffd84d"/><circle cx="315" cy="82" r="7" fill="#e3c7ff"/><path d="M296 32l5 10 11 2-8 8 2 11-10-5-10 5 2-11-8-8 11-2z" fill="#ffc83d"/>
 <g transform="translate(185 18)" filter="url(#soft)"><circle cx="66" cy="54" r="39" fill="#f2b47c"/><path d="M25 56Q24 10 66 7q39 1 40 47-17-22-42-22-22 0-39 24z" fill="#5a352d"/><path d="M35 47q-13-8-17 6 1 12 15 15M98 47q13-8 17 6-1 12-15 15" fill="#f2b47c"/><circle cx="52" cy="58" r="4" fill="#1f2430"/><circle cx="79" cy="58" r="4" fill="#1f2430"/><path d="M52 75q14 11 28 0" fill="none" stroke="#b95f5d" strokeWidth="4" strokeLinecap="round"/><path d="M24 108q42-29 84 0l11 67H12z" fill="url(#shirt)"/><rect x="48" y="112" width="38" height="52" rx="5" fill="#6b3bc6"/><path d="M57 126l10-9 10 9-4 14 9 8-13 1-7 12-6-12-13-1 9-8z" fill="#fff" opacity=".9"/><path d="M98 112q33-42 44-35" fill="none" stroke="#f2b47c" strokeWidth="15" strokeLinecap="round"/><path d="M141 77l8-13M141 77l17-3M141 77l12 11" stroke="#f2b47c" strokeWidth="8" strokeLinecap="round"/></g>
 <g transform="translate(25 126)"><rect width="78" height="18" rx="6" fill="#6d3de2"/><rect x="12" y="-17" width="82" height="18" rx="6" fill="#f1a63e"/><rect x="28" y="-34" width="76" height="18" rx="6" fill="#3caf68"/><rect x="118" y="-20" width="42" height="34" rx="5" fill="#8a54e9"/><path d="M139-20v-28" stroke="#5c9143" strokeWidth="5"/><path d="M139-47q-22-20-30 1 20 11 30-1zm0 0q22-20 30 1-20 11-30-1z" fill="#65b85d"/></g>
 </svg>}

function DailySummary({mobile=false}:{mobile?:boolean}){return <aside className={`summary-card premium-card ${mobile?'summary-mobile':'summary-desktop'}`}><div className="summary-head"><h2>Resumen del día</h2><span><CalendarDays size={14}/> Hoy</span></div><div className="summary-grid"><div className="summary-stat violet"><Users/><strong>28</strong><span>estudiantes activos</span></div><div className="summary-stat mint"><Target/><strong>15</strong><span>actividades realizadas</span></div><div className="summary-stat cyan"><Clock3/><strong>2h 35m</strong><span>tiempo de aprendizaje</span></div><div className="summary-stat yellow"><Trophy/><strong>12</strong><span>logros obtenidos</span></div></div></aside>}

export default function Dashboard(){return <AppShell active="Inicio"><div className="premium-dashboard canonical-dashboard approved-mobile-dashboard">
 <section className="welcome-grid">
  <div className="welcome-card premium-card"><div className="welcome-copy"><h1>¡Bienvenida de vuelta, Elba! 👋</h1><p>Hoy es un gran día para inspirar y transformar aprendizajes.</p></div><WelcomeTeacher/><div className="welcome-actions"><Link href="/crear" className="welcome-action purple"><span className="action-icon"><Sparkles/></span><span><b>Crear actividad</b><small>Diseña experiencias de aprendizaje increíbles.</small></span><ChevronRight className="action-chevron"/></Link><Link href="/biblioteca" className="welcome-action green"><span className="action-icon"><BookOpen/></span><span><b>Buscar recursos</b><small>Explora materiales listos para usar en tu clase.</small></span><ChevronRight className="action-chevron"/></Link><Link href="/juegos" className="welcome-action blue"><span className="action-icon"><Gamepad2/></span><span><b>Juego aleatorio</b><small>Aprender jugando es más divertido.</small></span><ChevronRight className="action-chevron"/></Link><Link href="/evaluaciones" className="welcome-action orange"><span className="action-icon"><ClipboardCheck/></span><span><b>Rúbricas</b><small>Evalúa y da seguimiento con facilidad.</small></span><ChevronRight className="action-chevron"/></Link></div></div>
  <DailySummary/>
 </section>
 <section className="dashboard-middle">
  <div className="featured-game premium-card canonical-featured"><ForestHeroArt/><div className="featured-overlay"></div><div className="featured-copy"><span>Juego inmersivo destacado</span><h2>La Aventura del Bosque Mágico</h2><p>Ayuda a Luma a encontrar los objetos, escuchar pistas y resolver misiones de comprensión lectora.</p><div className="game-cta"><Link href="/juegos" className="featured-play">Iniciar juego <span>▶</span></Link></div><div className="featured-progress"><div><small>Progreso del juego</small><span><i style={{width:'60%'}}></i></span><strong>60%</strong></div><div><small>Pistas encontradas</small><strong>2 / 4</strong><Search size={18}/></div></div></div><div className="featured-controls"><button aria-label="Música"><Music/></button><button aria-label="Sonido"><Volume2/></button></div></div>
  <DailySummary mobile/>
  <aside className="upcoming premium-card"><div className="section-title"><h2>Próximas actividades</h2><Link href="/biblioteca">Ver todas</Link></div>{premiumActivities.slice(0,3).map((a,i)=><Link href={`/biblioteca/${a.slug}`} className="upcoming-item" key={a.slug}><div className={`upcoming-thumb theme-${i}`}><ActivityArtwork kind={artKinds[i]}/></div><div><small>{a.format}</small><b>{a.title}</b><span>{a.subject} · {a.oa}</span></div><em><CalendarDays size={15}/>{i===0?'Hoy':i===1?'Mañana':'Viernes'}</em></Link>)}</aside>
 </section>
 <section className="dashboard-bottom">
  <div className="recommendations premium-card"><div className="section-title"><div><h2>Recomendado para tus grupos</h2><p>Basado en el progreso y las necesidades de aprendizaje.</p></div><Link href="/biblioteca">Ver todas <ChevronRight size={15}/></Link></div><div className="recommendation-row">{recommended.map((a,i)=><article className={`recommend-card recommendation-${i}`} key={a.slug}><span>{a.subject}</span><ActivityArtwork kind={artKinds[i]}/><h3>{a.title}</h3><small>{a.oa} · {a.level}</small><Link href={`/biblioteca/${a.slug}`}>Abrir actividad</Link></article>)}</div></div>
 </section>
 </div></AppShell>}
