'use client'

import Link from 'next/link'
import {useEffect,useState} from 'react'
import {AppShell} from '@/components/AppShell'
import {ownerApplications,premiumGeneratorCapabilities,supportProfiles} from '@/lib/product/catalog'
import {Bell,Volume2,Sparkles,ShieldCheck,Accessibility,Palette,UserRound,School,Crown,Infinity,Boxes,ArrowRight,WalletCards,Settings2,Save,Bot,Activity,PlugZap} from 'lucide-react'

type SessionContext={displayName?:string;roleLabel?:string;plan?:'basic'|'premium'|'owner';isOwner?:boolean;aiUnlimited?:boolean;permissions?:{premiumResources?:boolean;managePlatform?:boolean;managePlans?:boolean;manageModules?:boolean;manageThemes?:boolean;managePayments?:boolean}}
type Preferences={displayName:string;specialty:string;country:string;defaultLevel:string;defaultSubject:string;defaultSupportProfile:string;preferredDuration:string;theme:string;audio:boolean;animations:boolean;reduced:boolean;contrast:boolean;notifications:boolean;aiApproval:boolean;virtualTeacherTone:string;virtualTeacherDepth:string}
const defaults:Preferences={displayName:'',specialty:'Educadora diferencial / PIE',country:'Chile',defaultLevel:'3.º básico',defaultSubject:'Lenguaje y Comunicación',defaultSupportProfile:'Acceso universal DUA',preferredDuration:'45 minutos',theme:'purple',audio:true,animations:true,reduced:false,contrast:false,notifications:true,aiApproval:true,virtualTeacherTone:'profesional_claro',virtualTeacherDepth:'completo'}
const levels=['Educación parvularia','1.º básico','2.º básico','3.º básico','4.º básico','5.º básico','6.º básico','7.º básico','8.º básico','1.º medio','2.º medio','3.º medio','4.º medio','Multinivel']
const subjects=['Lenguaje y Comunicación','Matemática','Ciencias Naturales','Historia, Geografía y Ciencias Sociales','Inglés','Orientación','Educación Parvularia','Interdisciplinario']

export default function Configuracion(){
 const[settings,setSettings]=useState<Preferences>(defaults)
 const[session,setSession]=useState<SessionContext|null>(null)
 const[status,setStatus]=useState('Preferencias listas para editar')
 const[saving,setSaving]=useState(false)
 const owner=session?.isOwner===true
 const toggle=(key:'audio'|'animations'|'reduced'|'contrast'|'notifications'|'aiApproval')=>setSettings(current=>({...current,[key]:!current[key]}))
 useEffect(()=>{
  fetch('/api/session/context',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(setSession).catch(()=>setSession(null))
  fetch('/api/profile/preferences',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>{if(data)setSettings(current=>({...current,...data}))}).catch(()=>null)
 },[])
 async function save(){
  if(saving)return
  setSaving(true);setStatus('Guardando perfil y preferencias...')
  try{
   const response=await fetch('/api/profile/preferences',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)})
   const data=await response.json()
   if(!response.ok)throw new Error(data.error||'No fue posible guardar.')
   window.dispatchEvent(new CustomEvent('yoyo:preferences-updated',{detail:settings}))
   setStatus('Perfil y preferencias guardados y aplicados correctamente')
  }
  catch(error){setStatus(error instanceof Error?error.message:'No fue posible guardar.')}
  finally{setSaving(false)}
 }
 return <AppShell active="Configuración">
  <section className="premium-hero"><span className="eyebrow">Perfil y configuración integral</span><h1>{owner?'Perfil Propietaria':'Personaliza YOYOLETRASAI'}</h1><p>{owner?'Control total del entorno, IA, módulos, preferencias pedagógicas y operación de la plataforma.':'Controla accesibilidad, multimedia, privacidad, Profesor Virtual y preferencias institucionales.'}</p><div className="tool-row" style={{marginTop:14}}><button className="btn btn-primary" onClick={save} disabled={saving}><Save size={16}/>{saving?'Guardando...':'Guardar perfil'}</button><span className="setting-note">{status}</span></div></section>
  {owner&&<section className="panel" style={{marginBottom:20}}><div className="settings-title"><Crown/><div><h2>Acceso Propietaria · sin límites</h2><p>Tu cuenta conserva acceso completo a IA, recursos premium y administración de YoYoLetrasAI.</p></div></div><div className="metric-grid"><div><strong><Infinity/></strong><span>IA ilimitada</span></div><div><strong>{ownerApplications.length}</strong><span>aplicaciones registradas</span></div><div><strong>Premium</strong><span>recursos y generadores</span></div><div><strong>100%</strong><span>control de plataforma</span></div></div><div className="tool-row" style={{marginTop:14}}><Link href="/evolucion" className="btn btn-soft"><Activity size={16}/>Evolución YOYO</Link><Link href="/estado-sistema" className="btn btn-soft"><ShieldCheck size={16}/>Estado del sistema</Link><Link href="/integraciones" className="btn btn-soft"><PlugZap size={16}/>Integraciones</Link></div></section>}
  <div className="settings-grid">
   <section className="settings-card"><div className="settings-title"><UserRound/><div><h2>Perfil profesional</h2><p>Identidad visible y especialidad de trabajo.</p></div></div><label>Nombre visible<input value={settings.displayName||session?.displayName||''} onChange={e=>setSettings(s=>({...s,displayName:e.target.value}))}/></label><label>Rol<input value={session?.roleLabel||'Profesional de educación'} readOnly/></label><label>Especialidad<input value={settings.specialty} onChange={e=>setSettings(s=>({...s,specialty:e.target.value}))} placeholder="Ej.: Educadora diferencial / Coordinación PIE"/></label></section>
   <section className="settings-card"><div className="settings-title"><School/><div><h2>Contexto educativo predeterminado</h2><p>Se reutiliza en Profesor Virtual y generadores.</p></div></div><label>País<select value={settings.country} onChange={e=>setSettings(s=>({...s,country:e.target.value}))}><option>Chile</option><option>Argentina</option><option>Perú</option><option>Colombia</option></select></label><label>Nivel principal<select value={settings.defaultLevel} onChange={e=>setSettings(s=>({...s,defaultLevel:e.target.value}))}>{levels.map(item=><option key={item}>{item}</option>)}</select></label><label>Asignatura principal<select value={settings.defaultSubject} onChange={e=>setSettings(s=>({...s,defaultSubject:e.target.value}))}>{subjects.map(item=><option key={item}>{item}</option>)}</select></label><label>Perfil de apoyo<select value={settings.defaultSupportProfile} onChange={e=>setSettings(s=>({...s,defaultSupportProfile:e.target.value}))}>{supportProfiles.map(item=><option key={item}>{item}</option>)}</select></label></section>
   <section className="settings-card"><div className="settings-title"><Bot/><div><h2>Profesor Virtual</h2><p>Configura cómo responde tu copiloto pedagógico.</p></div></div><label>Duración habitual<select value={settings.preferredDuration} onChange={e=>setSettings(s=>({...s,preferredDuration:e.target.value}))}><option>30 minutos</option><option>45 minutos</option><option>60 minutos</option><option>90 minutos</option><option>Secuencia de 3 clases</option><option>Unidad completa</option></select></label><label>Tono<select value={settings.virtualTeacherTone} onChange={e=>setSettings(s=>({...s,virtualTeacherTone:e.target.value}))}><option value="profesional_claro">Profesional y claro</option><option value="cercano">Cercano y práctico</option><option value="tecnico">Técnico especialista</option></select></label><label>Profundidad<select value={settings.virtualTeacherDepth} onChange={e=>setSettings(s=>({...s,virtualTeacherDepth:e.target.value}))}><option value="breve">Breve</option><option value="completo">Completo</option><option value="profundo">Profundo</option></select></label><Link href="/profesor-virtual" className="btn btn-primary">Abrir Profesor Virtual <ArrowRight size={16}/></Link></section>
   <section className="settings-card"><div className="settings-title"><Accessibility/><div><h2>Accesibilidad</h2><p>Preferencias visuales y de movimiento.</p></div></div><button className={`setting-toggle ${settings.contrast?'on':''}`} onClick={()=>toggle('contrast')}><span>Alto contraste</span><i/></button><button className={`setting-toggle ${settings.reduced?'on':''}`} onClick={()=>toggle('reduced')}><span>Movimiento reducido</span><i/></button></section>
   <section className="settings-card"><div className="settings-title"><Volume2/><div><h2>Audio y animaciones</h2><p>Controla sonidos, narración y movimiento.</p></div></div><button className={`setting-toggle ${settings.audio?'on':''}`} onClick={()=>toggle('audio')}><span>Audio y narración</span><i/></button><button className={`setting-toggle ${settings.animations?'on':''}`} onClick={()=>toggle('animations')}><span>Animaciones educativas</span><i/></button></section>
   <section className="settings-card"><div className="settings-title"><Sparkles/><div><h2>YOYO IA</h2><p>IA pedagógica propia y vinculada a los módulos.</p></div></div><button className={`setting-toggle ${settings.aiApproval?'on':''}`} onClick={()=>toggle('aiApproval')}><span>Solicitar aprobación antes de acciones sensibles</span><i/></button><p className="setting-note">{session?.aiUnlimited?'Tu perfil dispone de uso ilimitado.':'El uso depende del plan activo.'}</p><Link href="/crear" className="btn btn-primary">Abrir generador premium <ArrowRight size={16}/></Link></section>
   <section className="settings-card"><div className="settings-title"><Bell/><div><h2>Notificaciones</h2><p>Alertas pedagógicas y administrativas.</p></div></div><button className={`setting-toggle ${settings.notifications?'on':''}`} onClick={()=>toggle('notifications')}><span>Notificaciones prioritarias</span><i/></button></section>
   <section className="settings-card"><div className="settings-title"><Palette/><div><h2>Apariencia</h2><p>Aplica el tema elegido a la experiencia global de YOYO.</p></div></div><div className="theme-options"><button aria-label="Tema morado" onClick={()=>setSettings(s=>({...s,theme:'purple'}))} className={`theme-dot purple ${settings.theme==='purple'?'active':''}`}/><button aria-label="Tema turquesa" onClick={()=>setSettings(s=>({...s,theme:'teal'}))} className={`theme-dot teal ${settings.theme==='teal'?'active':''}`}/><button aria-label="Tema coral" onClick={()=>setSettings(s=>({...s,theme:'coral'}))} className={`theme-dot coral ${settings.theme==='coral'?'active':''}`}/><button aria-label="Tema dorado" onClick={()=>setSettings(s=>({...s,theme:'gold'}))} className={`theme-dot gold ${settings.theme==='gold'?'active':''}`}/></div></section>
   <section className="settings-card"><div className="settings-title"><ShieldCheck/><div><h2>Privacidad y seguridad</h2><p>Accesos reales a control y auditoría.</p></div></div><Link href="/estado-sistema" className="btn btn-soft">Estado y seguridad</Link>{owner&&<Link href="/qa-publicacion" className="btn btn-soft">QA y publicación</Link>}</section>
  </div>
  {owner&&<><section className="panel" style={{marginTop:20}}><div className="settings-title"><Boxes/><div><h2>Aplicaciones y módulos de Propietaria</h2><p>Inventario operativo para administrar y evolucionar cada experiencia.</p></div></div><div className="game-experience-catalog">{ownerApplications.map(app=><article className="game-experience-card" key={app.href}><small>{app.category}</small><h3>{app.label}</h3><p>{app.description}</p><Link className="game-card-action" href={app.href}>Abrir aplicación <ArrowRight size={16}/></Link></article>)}</div></section><section className="panel" style={{marginTop:20}}><div className="settings-title"><Settings2/><div><h2>Control premium de plataforma</h2><p>Acceso a módulos, apariencia, planes, integraciones y evolución.</p></div></div><div className="tool-row"><Link href="/evolucion" className="btn btn-soft"><Activity size={16}/>Evolución</Link><Link href="/integraciones" className="btn btn-soft"><Boxes size={16}/>Integraciones</Link><Link href="/configuracion" className="btn btn-soft"><Palette size={16}/>Temas y perfil</Link><Link href="/planes" className="btn btn-soft"><WalletCards size={16}/>Planes</Link></div><div className="insight" style={{marginTop:14}}><b>Generador Premium</b>{premiumGeneratorCapabilities.map(item=><p key={item}>✓ {item}</p>)}</div></section></>}
 </AppShell>
}
