import {cloudflareChatCompletion,getCloudflareAIConfig} from '@/lib/ai/cloudflare-gateway'

export type ResourceFactoryDb={
 from:(table:string)=>{
  insert:(values:Record<string,unknown>|Record<string,unknown>[])=>any
  update:(values:Record<string,unknown>)=>any
 }
}

type DraftResource={
 resourceKeySuffix:string
 title:string
 level:string
 subject:string
 objective:string
 type:string
 studentVersion:Record<string,unknown>
 teacherVersion:Record<string,unknown>
 answerKey:unknown
 duaPie:Record<string,unknown>
 accessibility:Record<string,unknown>
}

function extractJsonArray(text:string):DraftResource[]{
 const trimmed=text.trim()
 const fenced=trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1]?.trim()||trimmed
 const first=fenced.indexOf('['),last=fenced.lastIndexOf(']')
 if(first<0||last<=first)throw new Error('RESOURCE_FACTORY_INVALID_JSON')
 const parsed=JSON.parse(fenced.slice(first,last+1)) as unknown
 if(!Array.isArray(parsed))throw new Error('RESOURCE_FACTORY_INVALID_ARRAY')
 const rows=parsed.slice(0,3).filter((item):item is DraftResource=>{
  if(!item||typeof item!=='object')return false
  const row=item as Record<string,unknown>
  return typeof row.resourceKeySuffix==='string'&&typeof row.title==='string'&&typeof row.level==='string'&&typeof row.subject==='string'&&typeof row.objective==='string'&&typeof row.type==='string'&&!!row.studentVersion&&!!row.teacherVersion
 })
 if(rows.length<3)throw new Error('RESOURCE_FACTORY_INCOMPLETE_BATCH')
 return rows
}

export async function generateResourceDraftBatch(db:ResourceFactoryDb,organizationId:string){
 const config=getCloudflareAIConfig()
 if(!config.configured)return {status:'skipped' as const,reason:'ai-not-configured'}

 const runInsert=await db.from('resource_factory_runs').insert({
  organization_id:organizationId,
  triggered_by:'scheduled',
  status:'running',
  requested_count:3,
  generated_count:0,
  published_count:0,
  metadata:{governance:'draft-only',reviewRequired:true,source:'evolution-72h'},
  started_at:new Date().toISOString(),
 }).select('id').single()
 if(runInsert.error||!runInsert.data?.id)throw new Error(runInsert.error?.message||'RESOURCE_FACTORY_RUN_START_FAILED')
 const runId=String(runInsert.data.id)

 try{
  const model=process.env.YOYO_AI_MODEL_OWNER?.trim()||process.env.YOYO_AI_MODEL_ADVANCED?.trim()||'anthropic/claude-sonnet-4-5'
  const result=await cloudflareChatCompletion({
   model,
   maxTokens:5200,
   temperature:.55,
   messages:[
    {role:'system',content:'Eres YOYO IA, motor pedagógico propio de una plataforma educativa chilena. Genera recursos originales, variados, profesionales, inclusivos y listos para revisión humana. No inventes códigos OA. Si no puedes verificar un código curricular oficial, usa sólo objetivo pedagógico redactado en lenguaje natural. No incluyas datos personales de estudiantes ni diagnósticos. No copies contenido propietario de otras plataformas.'},
    {role:'user',content:'Genera exactamente 3 recursos educativos distintos entre sí para biblioteca premium. Deben cubrir niveles o asignaturas diferentes y evitar repetir la misma mecánica. Devuelve SOLO un arreglo JSON válido con 3 objetos y estas claves exactas: resourceKeySuffix, title, level, subject, objective, type, studentVersion, teacherVersion, answerKey, duaPie, accessibility. resourceKeySuffix debe ser corto, minúsculo y con guiones. studentVersion y teacherVersion deben ser objetos completos. duaPie y accessibility deben incluir apoyos concretos. No incluyas ningún código OA. No agregues markdown.'},
   ],
  })
  const drafts=extractJsonArray(result.text)
  const cycle=new Date().toISOString().slice(0,10).replaceAll('-','')
  const qualityReport={
   reviewRequired:true,
   generatedBy:'YOYO IA',
   curricularAlignment:false,
   duaPie:false,
   accessibility:false,
   teacherVersion:false,
   studentVersion:false,
   answerKeyOrRubric:false,
   editableReusable:false,
   visualQuality:false,
  }
  const rows=drafts.map((draft,index)=>({
   organization_id:organizationId,
   factory_run_id:runId,
   resource_key:`auto-${cycle}-${index+1}-${draft.resourceKeySuffix.toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').slice(0,60)}`,
   title:draft.title.slice(0,180),
   payload:{
    type:draft.type,
    level:draft.level,
    subject:draft.subject,
    objective:draft.objective,
    premium:true,
    autoGenerated:true,
    reviewRequired:true,
    studentVersion:draft.studentVersion,
    teacherVersion:draft.teacherVersion,
    answerKey:draft.answerKey,
    duaPie:draft.duaPie,
    accessibility:draft.accessibility,
   },
   quality_score:null,
   quality_report:qualityReport,
   status:'draft',
  }))
  const inserted=await db.from('resource_candidates').insert(rows).select('id')
  if(inserted.error)throw new Error(inserted.error.message||'RESOURCE_FACTORY_INSERT_FAILED')
  await db.from('resource_factory_runs').update({status:'completed',generated_count:rows.length,published_count:0,completed_at:new Date().toISOString(),metadata:{governance:'draft-only',reviewRequired:true,source:'evolution-72h',model}}).eq('id',runId)
  return {status:'generated' as const,runId,generated:rows.length}
 }catch(error){
  await db.from('resource_factory_runs').update({status:'failed',completed_at:new Date().toISOString(),metadata:{governance:'draft-only',reviewRequired:true,source:'evolution-72h',error:error instanceof Error?error.message.slice(0,300):'RESOURCE_FACTORY_FAILED'}}).eq('id',runId)
  throw error
 }
}
