'use client'
import {useMemo,useState} from 'react'
import Link from 'next/link'
import {useParams} from 'next/navigation'
import {AppShell} from '@/components/AppShell'
import {resources} from '@/lib/resources'
const questions={
 'comprension-bosque-nativo':['¿Qué característica ayuda a conservar la humedad del bosque?','¿Por qué el bosque nativo es importante para los animales?','Escribe una inferencia usando una pista del texto.'],
 'valor-posicional':['Representa 347 con centenas, decenas y unidades.','¿Qué valor tiene el dígito 4 en 347?','Construye otro número con 3 centenas.'],
 'tabla-del-6':['Resuelve 6 × 4.','Completa: 6 × __ = 42.','Explica una estrategia para calcular 6 × 8.'],
 'conciencia-fonologica':['Selecciona la imagen que comienza con /m/.','Separa en sílabas la palabra “mano”.','Nombra otra palabra que comience con /m/.'],
 'ciclo-del-agua':['Ordena evaporación, condensación y precipitación.','¿Qué provoca la evaporación?','Explica el ciclo con tus palabras.'],
 'rutina-visual':['Ordena los pasos para iniciar una tarea.','Marca el paso que ya completaste.','Elige qué apoyo necesitas.']
} as Record<string,string[]>
export default function Recurso(){const params=useParams();const slug=String(params.slug);const resource=resources.find(r=>r.slug===slug)||resources[0];const qs=questions[slug]||questions['comprension-bosque-nativo'];const[selected,setSelected]=useState<number|null>(null);const[done,setDone]=useState(false);const options=useMemo(()=>slug==='valor-posicional'?['3 centenas, 4 decenas y 7 unidades','34 centenas y 7 unidades','3 decenas y 47 unidades']:['Porque sus árboles y plantas protegen el suelo','Porque no viven animales','Porque siempre hace calor'],[slug]);return <AppShell active="Biblioteca"><section className="premium-hero"><span className="eyebrow">{resource.subject} · {resource.level}</span><h1>{resource.title}</h1><p>{resource.desc}</p><div className="hero-cta"><button className="btn btn-coral" onClick={()=>setDone(true)}>Aplicar actividad</button><Link className="btn btn-soft" href="/crear">Crear versión adaptada</Link></div></section><div className="resource-detail"><section className="activity-preview"><span className="tag">Actividad interactiva visible</span><h2>{qs[0]}</h2><div style={{fontSize:72,textAlign:'center',padding:'20px'}}>{resource.emoji}</div>{options.map((o,i)=><button key={o} className="question-option" onClick={()=>setSelected(i)} style={selected===i?{borderColor:'#2e7f91',background:'#eaf4ef'}:{}}>{String.fromCharCode(65+i)}. {o}</button>)}<div className="feedback-box">{selected===null?'Selecciona una alternativa para recibir retroalimentación.':selected===0?'¡Correcto! La respuesta se relaciona con la información principal.':'Revisa nuevamente la pista y compara las alternativas.'}</div><h3 style={{marginTop:28}}>Siguiente desafío</h3><p>{qs[1]}</p><textarea rows={4} placeholder="Escribe o dicta tu respuesta..." style={{width:'100%'}}/><button className="btn btn-primary" style={{marginTop:12}} onClick={()=>setDone(true)}>Guardar evidencia</button></section><aside className="panel"><h2>Paquete pedagógico</h2><div className="quality-list"><span>✓ Actividad digital</span><span>✓ Guía imprimible</span><span>✓ Versión con apoyos</span><span>✓ Pauta de corrección</span><span>✓ Ticket de salida</span><span>✓ Seguimiento por OA</span></div><div className="insight"><b>Estado</b><p>{done?'Evidencia guardada. YOYO preparará el siguiente paso pedagógico.':'Lista para aplicar al curso o a un grupo flexible.'}</p></div><Link className="btn btn-soft" href="/biblioteca">Volver a biblioteca</Link></aside></div></AppShell>}