export const resources = [
  {
    id: 'sonidos-m-p',
    title: 'Descubro los sonidos M y P',
    type: 'Ficha imprimible',
    level: 'Kínder',
    subject: 'Lenguaje',
    skill: 'Conciencia fonológica',
    duration: '25 min',
    difficulty: 'Inicial',
    icon: '🗣️',
    color: 'violet',
    objective: 'Reconocer el sonido inicial /m/ y /p/ en palabras familiares.',
    instruction: 'Nombra cada dibujo. Luego marca la letra con la que comienza.',
    exercises: [
      'Observa, nombra y escucha el sonido inicial.',
      'Encierra la letra M o P según corresponda.',
      'Dibuja una palabra que comience con M.'
    ],
    tags: ['PIE', 'Visual', 'Imprimible'],
    kind: 'phonics',
  },
  {
    id: 'silabas-directas',
    title: 'Leo y formo sílabas directas',
    type: 'Cuadernillo',
    level: '1° básico',
    subject: 'Lenguaje',
    skill: 'Lectoescritura inicial',
    duration: '35 min',
    difficulty: 'Inicial',
    icon: '🔤',
    color: 'blue',
    objective: 'Leer y combinar sílabas directas con m, p, l y s.',
    instruction: 'Lee cada sílaba, únelas y escribe la palabra que se forma.',
    exercises: ['Lee en voz alta la familia silábica.', 'Forma cuatro palabras.', 'Completa la oración con la palabra correcta.'],
    tags: ['Lectura', 'Editable', 'Imprimible'],
    kind: 'syllables',
  },
  {
    id: 'sumas-visuales',
    title: 'Sumas y restas con apoyo visual',
    type: 'Guía adaptada',
    level: '1° básico',
    subject: 'Matemática',
    skill: 'Operatoria básica',
    duration: '30 min',
    difficulty: 'Inicial',
    icon: '➕',
    color: 'mint',
    objective: 'Resolver adiciones y sustracciones hasta 20 utilizando representaciones visuales.',
    instruction: 'Cuenta los elementos, representa la operación y escribe el resultado.',
    exercises: ['Cuenta y suma.', 'Tacha y resta.', 'Representa una operación con dibujos.'],
    tags: ['Concreto', 'PIE', 'Imprimible'],
    kind: 'math',
  },
  {
    id: 'trazos-basicos',
    title: 'Trazos que preparan mi escritura',
    type: 'Plantilla grafomotora',
    level: 'Prekínder',
    subject: 'Grafomotricidad',
    skill: 'Coordinación visomotora',
    duration: '20 min',
    difficulty: 'Inicial',
    icon: '✍️',
    color: 'peach',
    objective: 'Fortalecer el control del trazo mediante recorridos amplios y patrones progresivos.',
    instruction: 'Repasa lentamente cada camino desde el punto verde hasta la estrella.',
    exercises: ['Trazo horizontal.', 'Trazo ondulado.', 'Trazo circular.'],
    tags: ['Motricidad', 'Visual', 'Imprimible'],
    kind: 'tracing',
  },
  {
    id: 'comprension-zorro',
    title: 'El zorro y la lluvia',
    type: 'Lectura graduada',
    level: '3° básico',
    subject: 'Lenguaje',
    skill: 'Comprensión lectora',
    duration: '40 min',
    difficulty: 'Intermedia',
    icon: '🦊',
    color: 'amber',
    objective: 'Localizar información explícita e inferir una emoción en un texto narrativo breve.',
    instruction: 'Lee el texto con calma y responde usando información de la lectura.',
    exercises: ['Identifica al personaje principal.', 'Ordena tres acciones.', 'Explica cómo se siente el zorro.'],
    tags: ['Lectura', 'DUA', 'Audio'],
    kind: 'reading',
  },
  {
    id: 'fracciones-cotidianas',
    title: 'Fracciones en situaciones cotidianas',
    type: 'Actividad interactiva',
    level: '5° básico',
    subject: 'Matemática',
    skill: 'Representación de fracciones',
    duration: '45 min',
    difficulty: 'Intermedia',
    icon: '🍕',
    color: 'rose',
    objective: 'Representar fracciones propias mediante modelos concretos y gráficos.',
    instruction: 'Observa cada situación, colorea la parte indicada y escribe la fracción.',
    exercises: ['Representa 1/2.', 'Compara 2/4 y 3/4.', 'Crea un ejemplo de 3/8.'],
    tags: ['Interactivo', 'Visual', 'Editable'],
    kind: 'fractions',
  },
  {
    id: 'ecosistemas-chile',
    title: 'Ecosistemas de Chile',
    type: 'Organizador visual',
    level: '4° básico',
    subject: 'Ciencias',
    skill: 'Clasificar y relacionar',
    duration: '45 min',
    difficulty: 'Intermedia',
    icon: '🌿',
    color: 'green',
    objective: 'Relacionar seres vivos con las condiciones de distintos ecosistemas chilenos.',
    instruction: 'Observa las pistas y relaciona cada ser vivo con su ecosistema.',
    exercises: ['Compara desierto y bosque.', 'Clasifica cuatro seres vivos.', 'Explica una adaptación.'],
    tags: ['Chile', 'Visual', 'Currículum'],
    kind: 'science',
  },
  {
    id: 'emociones-semaforo',
    title: 'Semáforo para regular mis emociones',
    type: 'Apoyo socioemocional',
    level: 'Educación básica',
    subject: 'Orientación',
    skill: 'Autorregulación',
    duration: '15 min',
    difficulty: 'Flexible',
    icon: '🚦',
    color: 'sky',
    objective: 'Reconocer el nivel de activación emocional y seleccionar una estrategia de regulación.',
    instruction: 'Identifica cómo está tu cuerpo, elige un color y prueba una estrategia.',
    exercises: ['Me detengo.', 'Respiro y pienso.', 'Elijo una acción segura.'],
    tags: ['TEA', 'Convivencia', 'Visual'],
    kind: 'emotions',
  },
  {
    id: 'grafomotricidad-progresiva', title: 'Ruta grafomotora progresiva', type: 'Cuadernillo de 12 estaciones', level: 'Prekínder', subject: 'Grafomotricidad', skill: 'Precisión y direccionalidad', duration: '4 sesiones', difficulty: 'Progresiva', icon: '〰️', color: 'violet',
    objective: 'Consolidar el control del trazo desde movimientos simples hasta combinaciones previas a la escritura.',
    instruction: 'Sigue la secuencia: vertical, horizontal, diagonal, curva, círculo, espiral, onda, zigzag, bucle, arco y combinaciones.',
    exercises: ['Trazos verticales y horizontales.', 'Diagonales, curvas y círculos.', 'Espirales, ondas y zigzag.', 'Bucles, arcos y patrones combinados.'],
    tags: ['PIE', 'Progresión', 'Imprimible'], kind: 'tracing-complete',
  },
  {
    id: 'caligrafia-imprenta-cursiva', title: 'Caligrafía: imprenta y cursiva', type: 'Cuadernillo editable', level: '1° básico', subject: 'Lenguaje', skill: 'Escritura manuscrita', duration: '6 sesiones', difficulty: 'Progresiva', icon: '✒️', color: 'blue',
    objective: 'Escribir letras y palabras legibles en imprenta y cursiva respetando punto de inicio, dirección y tamaño.',
    instruction: 'Observa la flecha de inicio, repasa el modelo y luego escribe de forma autónoma.',
    exercises: ['Repasa minúsculas de imprenta.', 'Practica enlaces cursivos.', 'Copia palabras frecuentes.', 'Escribe una oración breve.'],
    tags: ['Direccionalidad', 'Caligrafía', 'Imprimible'], kind: 'handwriting',
  },
  {
    id: 'tablas-6-7', title: 'Estrategias para las tablas del 6 y 7', type: 'Guía con práctica', level: '4° básico', subject: 'Matemática', skill: 'Multiplicación', duration: '45 min', difficulty: 'Intermedia', icon: '✖️', color: 'mint',
    objective: 'Construir y aplicar las tablas del 6 y 7 usando descomposición, dobles y patrones.',
    instruction: 'Completa cada estrategia y explica qué patrón utilizaste.',
    exercises: ['Descompón 6 × n en 5 × n + n.', 'Construye la tabla del 7.', 'Resuelve problemas de agrupación.', 'Comprueba con suma reiterada.'],
    tags: ['Currículum', 'Estrategias', 'Editable'], kind: 'multiplication',
  },
  {
    id: 'angulos-entorno', title: 'Cazadores de ángulos', type: 'Laboratorio matemático', level: '4° básico', subject: 'Matemática', skill: 'Geometría', duration: '40 min', difficulty: 'Intermedia', icon: '📐', color: 'amber',
    objective: 'Reconocer, estimar y clasificar ángulos agudos, rectos y obtusos en objetos del entorno.',
    instruction: 'Compara cada abertura con un ángulo recto y registra tu clasificación.',
    exercises: ['Identifica cinco ángulos.', 'Clasifica por abertura.', 'Dibuja un ejemplo de cada tipo.', 'Justifica una clasificación.'],
    tags: ['Geometría', 'Manipulativo', 'Currículum'], kind: 'angles',
  },
  {
    id: 'pueblos-originarios', title: 'Pueblos originarios: territorio y legado', type: 'Mapa de aprendizaje', level: '4° básico', subject: 'Historia', skill: 'Ubicación y continuidad cultural', duration: '45 min', difficulty: 'Intermedia', icon: '🗺️', color: 'peach',
    objective: 'Relacionar pueblos originarios de Chile con sus territorios y reconocer aportes presentes.',
    instruction: 'Ubica, relaciona y explica usando las evidencias de las tarjetas informativas.',
    exercises: ['Ubica norte, centro y sur.', 'Relaciona pueblo y territorio.', 'Distingue pasado y presente.', 'Explica un aporte cultural.'],
    tags: ['Chile', 'Currículum', 'Visual'], kind: 'history',
  },
  {
    id: 'ciclo-agua', title: 'El viaje de una gota de agua', type: 'Secuencia científica', level: '2° básico', subject: 'Ciencias', skill: 'Explicar procesos', duration: '40 min', difficulty: 'Inicial', icon: '💧', color: 'sky',
    objective: 'Describir cambios y movimientos del agua mediante un modelo simple del ciclo del agua.',
    instruction: 'Ordena las etapas y explica el recorrido de la gota con tus palabras.',
    exercises: ['Observa el modelo.', 'Ordena evaporación, condensación y precipitación.', 'Representa el ciclo.', 'Explica dónde vuelve el agua.'],
    tags: ['Experimento', 'Visual', 'DUA'], kind: 'water-cycle',
  },
  {
    id: 'evaluacion-lectura-diversificada', title: 'Evaluación diversificada de lectura', type: 'Evaluación editable', level: '3° básico', subject: 'Lenguaje', skill: 'Comprensión lectora', duration: '45 min', difficulty: 'Flexible', icon: '✅', color: 'rose',
    objective: 'Evidenciar comprensión literal e inferencial mediante distintas formas de respuesta.',
    instruction: 'Lee o escucha el texto y responde escribiendo, marcando, dibujando o explicando oralmente.',
    exercises: ['Reconoce información explícita.', 'Ordena la secuencia.', 'Infiere una emoción.', 'Explica con una evidencia.'],
    tags: ['Evaluación', 'PIE', 'DUA'], kind: 'assessment',
  },
];

export const modules = [
  { id: 'library', label: 'Biblioteca', icon: '▦', description: 'Materiales listos para usar', tone: 'violet', group: 'Docencia' },
  { id: 'creator', label: 'YOYO IA', icon: '✦', description: 'Crea actividades, imágenes, informes, presentaciones y videos', tone: 'blue', group: 'Docencia' },
  { id: 'research', label: 'Investigación', icon: '⌕', description: 'Busca, contrasta y cita fuentes verificables', tone: 'violet', group: 'Docencia' },
  { id: 'reader', label: 'Plan lector', icon: '▣', description: 'Rutas de lectura, evidencias y vínculo familiar', tone: 'green', group: 'Docencia' },
  { id: 'teacher', label: 'Profesor virtual', icon: '◌', description: 'Tutoría guiada y segura', tone: 'rose', group: 'Docencia' },
  { id: 'math', label: 'Laboratorio matemático', icon: '∑', description: 'Practica con retroalimentación', tone: 'amber', group: 'Docencia' },
  { id: 'games', label: 'YOYO Play', icon: '◆', description: 'Mundos 3D, sonido, niveles y aventuras', tone: 'rose', group: 'Herramientas' },
  { id: 'notebook', label: 'Fuentes IA', icon: '⇧', description: 'Sube archivos, analiza, resume y crea con citas', tone: 'blue', group: 'Herramientas' },
  { id: 'planning', label: 'Planificaciones', icon: '▧', description: 'Clases alineadas y DUA', tone: 'green', group: 'Herramientas' },
  { id: 'assessments', label: 'Evaluaciones', icon: '✓', description: 'Evidencias diversificadas', tone: 'mint', group: 'Herramientas' },
  { id: 'multimedia', label: 'Multimedia', icon: '▶', description: 'Presentaciones pedagógicas', tone: 'amber', group: 'Herramientas' },
  { id: 'pictograms', label: 'Pictogramas', icon: '◫', description: 'Secuencias visuales accesibles', tone: 'sky', group: 'Herramientas' },
  { id: 'classes', label: 'Mis cursos', icon: '◉', description: 'Asignaciones y seguimiento', tone: 'violet', group: 'Comunidad' },
  { id: 'student', label: 'Espacio estudiante', icon: '★', description: 'Ruta accesible y motivadora', tone: 'amber', group: 'Comunidad' },
  { id: 'pie', label: 'PIE y DUA', icon: '♿', description: 'Adaptaciones sin bajar objetivos', tone: 'sky', group: 'Comunidad' },
  { id: 'families', label: 'Familias', icon: '♡', description: 'Orientaciones claras para el hogar', tone: 'rose', group: 'Comunidad' },
  { id: 'institution', label: 'Institución', icon: '▰', description: 'Estado general del espacio', tone: 'blue', group: 'Gestión' },
  { id: 'progress', label: 'Progreso', icon: '↗', description: 'Seguimiento basado en evidencia', tone: 'green', group: 'Gestión' },
  { id: 'reports', label: 'Informes', icon: '▥', description: 'Borradores pedagógicos trazables', tone: 'violet', group: 'Gestión' },
];

export const navItems = [
  { id: 'dashboard', label: 'Inicio', icon: '⌂', section: 'ESPACIO DOCENTE' },
  { id: 'library', label: 'Biblioteca', icon: '▦', section: 'ESPACIO DOCENTE' },
  { id: 'creator', label: 'YOYO IA', icon: '✦', section: 'ESPACIO DOCENTE' },
  { id: 'research', label: 'Investigación', icon: '⌕', section: 'ESPACIO DOCENTE' },
  { id: 'reader', label: 'Plan lector', icon: '▣', section: 'ESPACIO DOCENTE' },
  { id: 'teacher', label: 'Profesor virtual', icon: '◌', section: 'ESPACIO DOCENTE' },
  { id: 'math', label: 'Laboratorio matemático', icon: '∑', section: 'ESPACIO DOCENTE' },
  { id: 'games', label: 'YOYO Play', icon: '◆', section: 'HERRAMIENTAS' },
  { id: 'notebook', label: 'Fuentes IA', icon: '⇧', section: 'HERRAMIENTAS' },
  { id: 'planning', label: 'Planificaciones', icon: '▧', section: 'HERRAMIENTAS' },
  { id: 'assessments', label: 'Evaluaciones', icon: '✓', section: 'HERRAMIENTAS' },
  { id: 'multimedia', label: 'Multimedia', icon: '▶', section: 'HERRAMIENTAS' },
  { id: 'pictograms', label: 'Pictogramas', icon: '◫', section: 'HERRAMIENTAS' },
  { id: 'classes', label: 'Mis cursos', icon: '◉', section: 'COMUNIDAD' },
  { id: 'student', label: 'Espacio estudiante', icon: '★', section: 'COMUNIDAD' },
  { id: 'pie', label: 'PIE y DUA', icon: '♿', section: 'COMUNIDAD' },
  { id: 'families', label: 'Familias', icon: '♡', section: 'COMUNIDAD' },
  { id: 'institution', label: 'Institución', icon: '▰', section: 'GESTIÓN' },
  { id: 'progress', label: 'Progreso', icon: '↗', section: 'GESTIÓN' },
  { id: 'reports', label: 'Informes', icon: '▥', section: 'GESTIÓN' },
  { id: 'owner', label: 'Perfil propietario', icon: '⚙', section: 'GESTIÓN' },
];